/**
 * NFL Methodology - Complete 110 Playbook Library Seed Data
 * Auto-generated from user-provided taxonomy
 */

import { db } from '../db';
import {
  playbookDomains,
  playbookCategories,
  playbookLibrary,
} from '@shared/schema';

export async function seedPlaybookLibrary() {
  console.log('🏈 Seeding Complete 110-Playbook Library...');

  // ========== DOMAIN 1: MARKET DYNAMICS (18 playbooks) ==========
  const [domain1] = await db.insert(playbookDomains).values({
    name: 'Market Dynamics',
    code: 'DOMAIN1',
    description: 'Competitive threats, market position shifts, and go-to-market challenges',
    icon: 'target',
    color: '#E74C3C',
    sequence: 1,
    primaryExecutiveRole: 'CEO',
    totalPlaybooks: 18,
  }).returning();

  const [cat1_1] = await db.insert(playbookCategories).values({
    domainId: domain1.id,
    name: 'Market Position Threats',
    description: 'New entrants, product launches, pricing wars',
    sequence: 1,
    totalPlaybooks: 10,
  }).returning();

  const [cat1_2] = await db.insert(playbookCategories).values({
    domainId: domain1.id,
    name: 'Go-to-Market Threats',
    description: 'Channel conflicts, customer defection, sales challenges',
    sequence: 2,
    totalPlaybooks: 8,
  }).returning();

  await db.insert(playbookLibrary).values([
    {
      playbookNumber: 1,
      domainId: domain1.id,
      categoryId: cat1_1.id,
      name: 'New Market Entrant (Funded Startup)',
      description: 'VC-backed competitor enters your core market segment',
      triggerCriteria: 'VC-backed competitor enters your core market segment',
      triggerDataSources: ['competitive_intelligence', 'market_data', 'news'],
      triggerThreshold: { confidence: 0.85 },
      tier1Stakeholders: ['CEO', 'CMO', 'CPO', 'Strategy'],
      tier2Stakeholders: ['Product', 'Marketing', 'Sales', 'Strategy'],
      tier3Stakeholders: ['All_Employees'],
      externalPartners: ['Strategy_Consultant', 'Legal_Counsel'],
      primaryResponseStrategy: 'Competitive positioning, pricing strategy, product acceleration',
      preApprovedBudget: 500000,
      budgetApprovalRequired: false,
      targetExecutionTime: 12,
      averageActivationFrequency: 'medium',
      historicalSuccessRate: 0.6625273772095631,
    },
    {
      playbookNumber: 2,
      domainId: domain1.id,
      categoryId: cat1_1.id,
      name: 'New Market Entrant (Established Player)',
      description: 'Fortune 500 company announces entry into your market',
      triggerCriteria: 'Fortune 500 company announces entry into your market',
      triggerDataSources: ['competitive_intelligence', 'market_data', 'news'],
      triggerThreshold: { confidence: 0.85 },
      tier1Stakeholders: ['CEO', 'Board', 'CFO', 'Strategy'],
      tier2Stakeholders: ['Product', 'Marketing', 'Sales', 'Strategy'],
      tier3Stakeholders: ['All_Employees'],
      externalPartners: ['Strategy_Consultant', 'Legal_Counsel'],
      primaryResponseStrategy: 'Partnership exploration, differentiation strategy, market defense',
      preApprovedBudget: 500000,
      budgetApprovalRequired: true,
      targetExecutionTime: 12,
      averageActivationFrequency: 'medium',
      historicalSuccessRate: 0.7916378048872027,
    },
    {
      playbookNumber: 3,
      domainId: domain1.id,
      categoryId: cat1_1.id,
      name: 'Competitor Product Launch (Feature Parity)',
      description: 'Competitor releases product matching your core capabilities',
      triggerCriteria: 'Competitor releases product matching your core capabilities',
      triggerDataSources: ['competitive_intelligence', 'market_data', 'news'],
      triggerThreshold: { confidence: 0.85 },
      tier1Stakeholders: ['CPO', 'CTO', 'CMO', 'Sales'],
      tier2Stakeholders: ['Product', 'Marketing', 'Sales', 'Strategy'],
      tier3Stakeholders: ['All_Employees'],
      externalPartners: ['Strategy_Consultant', 'Legal_Counsel'],
      primaryResponseStrategy: 'Feature acceleration, messaging pivot, customer retention',
      preApprovedBudget: 500000,
      budgetApprovalRequired: false,
      targetExecutionTime: 12,
      averageActivationFrequency: 'medium',
      historicalSuccessRate: 0.6712944207722265,
    },
    {
      playbookNumber: 4,
      domainId: domain1.id,
      categoryId: cat1_1.id,
      name: 'Competitor Product Launch (Breakthrough Innovation)',
      description: 'Competitor announces technology that leapfrogs your offerings',
      triggerCriteria: 'Competitor announces technology that leapfrogs your offerings',
      triggerDataSources: ['competitive_intelligence', 'market_data', 'news'],
      triggerThreshold: { confidence: 0.85 },
      tier1Stakeholders: ['CEO', 'CTO', 'CPO', 'Board'],
      tier2Stakeholders: ['Product', 'Marketing', 'Sales', 'Strategy'],
      tier3Stakeholders: ['All_Employees'],
      externalPartners: ['Strategy_Consultant', 'Legal_Counsel'],
      primaryResponseStrategy: 'Technology assessment, R&D pivot, market repositioning',
      preApprovedBudget: 500000,
      budgetApprovalRequired: true,
      targetExecutionTime: 12,
      averageActivationFrequency: 'medium',
      historicalSuccessRate: 0.8294198345051838,
    },
    {
      playbookNumber: 5,
      domainId: domain1.id,
      categoryId: cat1_1.id,
      name: 'Aggressive Pricing Disruption',
      description: 'Competitor cuts prices 30%+ or introduces disruptive pricing model',
      triggerCriteria: 'Competitor cuts prices 30%+ or introduces disruptive pricing model',
      triggerDataSources: ['competitive_intelligence', 'market_data', 'news'],
      triggerThreshold: { confidence: 0.85 },
      tier1Stakeholders: ['CFO', 'CMO', 'Sales', 'Pricing'],
      tier2Stakeholders: ['Product', 'Marketing', 'Sales', 'Strategy'],
      tier3Stakeholders: ['All_Employees'],
      externalPartners: ['Strategy_Consultant', 'Legal_Counsel'],
      primaryResponseStrategy: 'Value proposition reinforcement, pricing analysis, margin defense',
      preApprovedBudget: 500000,
      budgetApprovalRequired: false,
      targetExecutionTime: 12,
      averageActivationFrequency: 'medium',
      historicalSuccessRate: 0.6706547234767064,
    },
    {
      playbookNumber: 6,
      domainId: domain1.id,
      categoryId: cat1_1.id,
      name: 'Patent Infringement Claim (Incoming)',
      description: 'Competitor alleges your product infringes their patents',
      triggerCriteria: 'Competitor alleges your product infringes their patents',
      triggerDataSources: ['competitive_intelligence', 'market_data', 'news'],
      triggerThreshold: { confidence: 0.85 },
      tier1Stakeholders: ['CEO', 'CLO', 'CTO', 'Board'],
      tier2Stakeholders: ['Product', 'Marketing', 'Sales', 'Strategy'],
      tier3Stakeholders: ['All_Employees'],
      externalPartners: ['Strategy_Consultant', 'Legal_Counsel'],
      primaryResponseStrategy: 'Legal defense, product review, prior art search',
      preApprovedBudget: 750000,
      budgetApprovalRequired: false,
      targetExecutionTime: 12,
      averageActivationFrequency: 'low',
      historicalSuccessRate: 0.8212061439629039,
    },
    {
      playbookNumber: 7,
      domainId: domain1.id,
      categoryId: cat1_1.id,
      name: 'Patent Infringement Claim (Outgoing)',
      description: 'Discovery that competitor may be infringing your patents',
      triggerCriteria: 'Discovery that competitor may be infringing your patents',
      triggerDataSources: ['competitive_intelligence', 'market_data', 'news'],
      triggerThreshold: { confidence: 0.85 },
      tier1Stakeholders: ['CLO', 'CEO', 'CPO', 'Board'],
      tier2Stakeholders: ['Product', 'Marketing', 'Sales', 'Strategy'],
      tier3Stakeholders: ['All_Employees'],
      externalPartners: ['Strategy_Consultant', 'Legal_Counsel'],
      primaryResponseStrategy: 'Legal assessment, enforcement strategy, licensing negotiation',
      preApprovedBudget: 750000,
      budgetApprovalRequired: false,
      targetExecutionTime: 12,
      averageActivationFrequency: 'low',
      historicalSuccessRate: 0.708986271436163,
    },
    {
      playbookNumber: 8,
      domainId: domain1.id,
      categoryId: cat1_1.id,
      name: 'Key Talent Poaching Campaign',
      description: 'Competitor systematically recruiting your top talent (5+ departures)',
      triggerCriteria: 'Competitor systematically recruiting your top talent (5+ departures)',
      triggerDataSources: ['competitive_intelligence', 'market_data', 'news'],
      triggerThreshold: { confidence: 0.85 },
      tier1Stakeholders: ['CHRO', 'CEO', 'Business Unit Leads'],
      tier2Stakeholders: ['Product', 'Marketing', 'Sales', 'Strategy'],
      tier3Stakeholders: ['All_Employees'],
      externalPartners: ['Strategy_Consultant', 'Legal_Counsel'],
      primaryResponseStrategy: 'Retention offers, culture reinforcement, talent pipeline acceleration',
      preApprovedBudget: 750000,
      budgetApprovalRequired: false,
      targetExecutionTime: 12,
      averageActivationFrequency: 'low',
      historicalSuccessRate: 0.6530208248157098,
    },
    {
      playbookNumber: 9,
      domainId: domain1.id,
      categoryId: cat1_1.id,
      name: 'Competitor M&A (Consolidation)',
      description: 'Two competitors merge, creating larger rival',
      triggerCriteria: 'Two competitors merge, creating larger rival',
      triggerDataSources: ['competitive_intelligence', 'market_data', 'news'],
      triggerThreshold: { confidence: 0.85 },
      tier1Stakeholders: ['CEO', 'CFO', 'Strategy', 'Board'],
      tier2Stakeholders: ['Product', 'Marketing', 'Sales', 'Strategy'],
      tier3Stakeholders: ['All_Employees'],
      externalPartners: ['Strategy_Consultant', 'Legal_Counsel'],
      primaryResponseStrategy: 'Competitive reassessment, partnership exploration, market positioning',
      preApprovedBudget: 750000,
      budgetApprovalRequired: false,
      targetExecutionTime: 12,
      averageActivationFrequency: 'low',
      historicalSuccessRate: 0.6863969421756037,
    },
    {
      playbookNumber: 10,
      domainId: domain1.id,
      categoryId: cat1_1.id,
      name: 'Competitor Acquires Strategic Asset',
      description: 'Competitor buys key supplier, distributor, or technology company',
      triggerCriteria: 'Competitor buys key supplier, distributor, or technology company',
      triggerDataSources: ['competitive_intelligence', 'market_data', 'news'],
      triggerThreshold: { confidence: 0.85 },
      tier1Stakeholders: ['CEO', 'COO', 'Strategy'],
      tier2Stakeholders: ['Product', 'Marketing', 'Sales', 'Strategy'],
      tier3Stakeholders: ['All_Employees'],
      externalPartners: ['Strategy_Consultant', 'Legal_Counsel'],
      primaryResponseStrategy: 'Supply chain security, alternative partnerships, M&A response',
      preApprovedBudget: 750000,
      budgetApprovalRequired: false,
      targetExecutionTime: 12,
      averageActivationFrequency: 'low',
      historicalSuccessRate: 0.7703489712674869,
    },
    {
      playbookNumber: 11,
      domainId: domain1.id,
      categoryId: cat1_2.id,
      name: 'Channel Conflict (Direct vs. Partner)',
      description: 'Channel partners threaten to drop your product',
      triggerCriteria: 'Channel partners threaten to drop your product',
      triggerDataSources: ['competitive_intelligence', 'market_data', 'news'],
      triggerThreshold: { confidence: 0.85 },
      tier1Stakeholders: ['COO', 'Sales', 'Channel Management'],
      tier2Stakeholders: ['Product', 'Marketing', 'Sales', 'Strategy'],
      tier3Stakeholders: ['All_Employees'],
      externalPartners: ['Strategy_Consultant', 'Legal_Counsel'],
      primaryResponseStrategy: 'Partner negotiation, channel strategy revision, conflict resolution',
      preApprovedBudget: 300000,
      budgetApprovalRequired: false,
      targetExecutionTime: 12,
      averageActivationFrequency: 'low',
      historicalSuccessRate: 0.7457747412883042,
    },
    {
      playbookNumber: 12,
      domainId: domain1.id,
      categoryId: cat1_2.id,
      name: 'Customer Consolidation to Competitor',
      description: 'Major customer announces switch to competitor (>$5M ARR)',
      triggerCriteria: 'Major customer announces switch to competitor (>$5M ARR)',
      triggerDataSources: ['competitive_intelligence', 'market_data', 'news'],
      triggerThreshold: { confidence: 0.85 },
      tier1Stakeholders: ['CEO', 'Sales', 'Customer Success'],
      tier2Stakeholders: ['Product', 'Marketing', 'Sales', 'Strategy'],
      tier3Stakeholders: ['All_Employees'],
      externalPartners: ['Strategy_Consultant', 'Legal_Counsel'],
      primaryResponseStrategy: 'Save campaign, relationship repair, product gap analysis',
      preApprovedBudget: 300000,
      budgetApprovalRequired: false,
      targetExecutionTime: 12,
      averageActivationFrequency: 'low',
      historicalSuccessRate: 0.7994387239060872,
    },
    {
      playbookNumber: 13,
      domainId: domain1.id,
      categoryId: cat1_2.id,
      name: 'Sales Team Defection',
      description: 'Competitor hires your top sales reps (3+ in quarter)',
      triggerCriteria: 'Competitor hires your top sales reps (3+ in quarter)',
      triggerDataSources: ['competitive_intelligence', 'market_data', 'news'],
      triggerThreshold: { confidence: 0.85 },
      tier1Stakeholders: ['CRO', 'CHRO', 'CEO'],
      tier2Stakeholders: ['Product', 'Marketing', 'Sales', 'Strategy'],
      tier3Stakeholders: ['All_Employees'],
      externalPartners: ['Strategy_Consultant', 'Legal_Counsel'],
      primaryResponseStrategy: 'Client relationship protection, pipeline recovery, compensation review',
      preApprovedBudget: 300000,
      budgetApprovalRequired: false,
      targetExecutionTime: 12,
      averageActivationFrequency: 'low',
      historicalSuccessRate: 0.6807389470310342,
    },
    {
      playbookNumber: 14,
      domainId: domain1.id,
      categoryId: cat1_2.id,
      name: 'Geographic Market Entry by Competitor',
      description: 'Competitor enters your stronghold geography',
      triggerCriteria: 'Competitor enters your stronghold geography',
      triggerDataSources: ['competitive_intelligence', 'market_data', 'news'],
      triggerThreshold: { confidence: 0.85 },
      tier1Stakeholders: ['CEO', 'GM (Region)', 'Sales'],
      tier2Stakeholders: ['Product', 'Marketing', 'Sales', 'Strategy'],
      tier3Stakeholders: ['All_Employees'],
      externalPartners: ['Strategy_Consultant', 'Legal_Counsel'],
      primaryResponseStrategy: 'Regional defense, local partnerships, market protection',
      preApprovedBudget: 300000,
      budgetApprovalRequired: false,
      targetExecutionTime: 12,
      averageActivationFrequency: 'low',
      historicalSuccessRate: 0.8056776850792287,
    },
    {
      playbookNumber: 15,
      domainId: domain1.id,
      categoryId: cat1_2.id,
      name: 'Negative Comparison Campaign',
      description: 'Competitor launches marketing attacking your product',
      triggerCriteria: 'Competitor launches marketing attacking your product',
      triggerDataSources: ['competitive_intelligence', 'market_data', 'news'],
      triggerThreshold: { confidence: 0.85 },
      tier1Stakeholders: ['CMO', 'CLO', 'CEO'],
      tier2Stakeholders: ['Product', 'Marketing', 'Sales', 'Strategy'],
      tier3Stakeholders: ['All_Employees'],
      externalPartners: ['Strategy_Consultant', 'Legal_Counsel'],
      primaryResponseStrategy: 'Counter-messaging, factual correction, legal assessment',
      preApprovedBudget: 300000,
      budgetApprovalRequired: false,
      targetExecutionTime: 12,
      averageActivationFrequency: 'low',
      historicalSuccessRate: 0.7237144409002898,
    },
    {
      playbookNumber: 16,
      domainId: domain1.id,
      categoryId: cat1_2.id,
      name: 'Customer Advisory Board Defection',
      description: 'Strategic advisory board members join competitor board',
      triggerCriteria: 'Strategic advisory board members join competitor board',
      triggerDataSources: ['competitive_intelligence', 'market_data', 'news'],
      triggerThreshold: { confidence: 0.85 },
      tier1Stakeholders: ['CEO', 'Strategy', 'Customer Success'],
      tier2Stakeholders: ['Product', 'Marketing', 'Sales', 'Strategy'],
      tier3Stakeholders: ['All_Employees'],
      externalPartners: ['Strategy_Consultant', 'Legal_Counsel'],
      primaryResponseStrategy: 'Relationship repair, board reconstitution, loyalty reinforcement',
      preApprovedBudget: 300000,
      budgetApprovalRequired: false,
      targetExecutionTime: 12,
      averageActivationFrequency: 'rare',
      historicalSuccessRate: 0.7273851865971988,
    },
    {
      playbookNumber: 17,
      domainId: domain1.id,
      categoryId: cat1_2.id,
      name: 'Competitor Launches Free/Freemium Tier',
      description: 'Competitor introduces free version of paid product',
      triggerCriteria: 'Competitor introduces free version of paid product',
      triggerDataSources: ['competitive_intelligence', 'market_data', 'news'],
      triggerThreshold: { confidence: 0.85 },
      tier1Stakeholders: ['CPO', 'CMO', 'CFO', 'Pricing'],
      tier2Stakeholders: ['Product', 'Marketing', 'Sales', 'Strategy'],
      tier3Stakeholders: ['All_Employees'],
      externalPartners: ['Strategy_Consultant', 'Legal_Counsel'],
      primaryResponseStrategy: 'Business model assessment, value differentiation, customer communication',
      preApprovedBudget: 300000,
      budgetApprovalRequired: false,
      targetExecutionTime: 12,
      averageActivationFrequency: 'rare',
      historicalSuccessRate: 0.6834904692634525,
    },
    {
      playbookNumber: 18,
      domainId: domain1.id,
      categoryId: cat1_2.id,
      name: 'Industry Standards Battle',
      description: 'Competitor attempts to establish incompatible industry standard',
      triggerCriteria: 'Competitor attempts to establish incompatible industry standard',
      triggerDataSources: ['competitive_intelligence', 'market_data', 'news'],
      triggerThreshold: { confidence: 0.85 },
      tier1Stakeholders: ['CTO', 'Strategy', 'Standards Team'],
      tier2Stakeholders: ['Product', 'Marketing', 'Sales', 'Strategy'],
      tier3Stakeholders: ['All_Employees'],
      externalPartners: ['Strategy_Consultant', 'Legal_Counsel'],
      primaryResponseStrategy: 'Coalition building, standards participation, interoperability strategy',
      preApprovedBudget: 300000,
      budgetApprovalRequired: false,
      targetExecutionTime: 12,
      averageActivationFrequency: 'rare',
      historicalSuccessRate: 0.6528315613323793,
    }
  ]);

  console.log('✅ Domain 1: Market Dynamics - 18 playbooks seeded');

  // ========== DOMAIN 2: OPERATIONAL EXCELLENCE (16 playbooks) ==========
  const [domain2] = await db.insert(playbookDomains).values({
    name: 'Operational Excellence',
    code: 'DOMAIN2',
    description: 'Supply chain, facilities, infrastructure, and third-party dependencies',
    icon: 'truck',
    color: '#F39C12',
    sequence: 2,
    primaryExecutiveRole: 'COO',
    totalPlaybooks: 16,
  }).returning();

  const [cat2_1] = await db.insert(playbookCategories).values({
    domainId: domain2.id,
    name: 'Supply Chain Crises',
    description: 'Supplier failures, shortages, logistics disruptions',
    sequence: 1,
    totalPlaybooks: 6,
  }).returning();

  const [cat2_2] = await db.insert(playbookCategories).values({
    domainId: domain2.id,
    name: 'Facility & Infrastructure',
    description: 'Manufacturing, distribution, data center, safety incidents',
    sequence: 2,
    totalPlaybooks: 6,
  }).returning();

  const [cat2_3] = await db.insert(playbookCategories).values({
    domainId: domain2.id,
    name: 'Third-Party Dependencies',
    description: 'Vendor services, technology partners, critical integrations',
    sequence: 3,
    totalPlaybooks: 4,
  }).returning();

  await db.insert(playbookLibrary).values([
    {
      playbookNumber: 19,
      domainId: domain2.id,
      categoryId: cat2_1.id,
      name: 'Primary Supplier Failure',
      description: 'Main supplier experiences bankruptcy, fire, or production halt',
      triggerCriteria: 'Main supplier experiences bankruptcy, fire, or production halt',
      triggerDataSources: ['supply_chain', 'facilities', 'vendor_monitoring'],
      triggerThreshold: { confidence: 0.90 },
      tier1Stakeholders: ['COO', 'Procurement', 'Manufacturing'],
      tier2Stakeholders: ['Operations', 'Procurement', 'Quality', 'Safety'],
      tier3Stakeholders: ['All_Operations'],
      externalPartners: ['Logistics_Provider', 'Insurance'],
      primaryResponseStrategy: 'Alternative supplier activation, inventory management, production continuity',
      preApprovedBudget: 400000,
      budgetApprovalRequired: false,
      targetExecutionTime: 12,
      averageActivationFrequency: 'low',
      historicalSuccessRate: 0.7012920767621952,
    },
    {
      playbookNumber: 20,
      domainId: domain2.id,
      categoryId: cat2_1.id,
      name: 'Critical Component Shortage',
      description: 'Industry-wide shortage of essential component (chips, raw materials)',
      triggerCriteria: 'Industry-wide shortage of essential component (chips, raw materials)',
      triggerDataSources: ['supply_chain', 'facilities', 'vendor_monitoring'],
      triggerThreshold: { confidence: 0.90 },
      tier1Stakeholders: ['COO', 'CFO', 'Manufacturing', 'Procurement'],
      tier2Stakeholders: ['Operations', 'Procurement', 'Quality', 'Safety'],
      tier3Stakeholders: ['All_Operations'],
      externalPartners: ['Logistics_Provider', 'Insurance'],
      primaryResponseStrategy: 'Substitute sourcing, production prioritization, customer allocation',
      preApprovedBudget: 400000,
      budgetApprovalRequired: false,
      targetExecutionTime: 12,
      averageActivationFrequency: 'low',
      historicalSuccessRate: 0.7501375555219596,
    },
    {
      playbookNumber: 21,
      domainId: domain2.id,
      categoryId: cat2_1.id,
      name: 'Transportation/Logistics Disruption',
      description: 'Strike, natural disaster, or infrastructure failure blocks distribution',
      triggerCriteria: 'Strike, natural disaster, or infrastructure failure blocks distribution',
      triggerDataSources: ['supply_chain', 'facilities', 'vendor_monitoring'],
      triggerThreshold: { confidence: 0.90 },
      tier1Stakeholders: ['COO', 'Logistics', 'Customer Service'],
      tier2Stakeholders: ['Operations', 'Procurement', 'Quality', 'Safety'],
      tier3Stakeholders: ['All_Operations'],
      externalPartners: ['Logistics_Provider', 'Insurance'],
      primaryResponseStrategy: 'Alternative routing, customer communication, fulfillment workarounds',
      preApprovedBudget: 400000,
      budgetApprovalRequired: false,
      targetExecutionTime: 12,
      averageActivationFrequency: 'low',
      historicalSuccessRate: 0.7725365192930738,
    },
    {
      playbookNumber: 22,
      domainId: domain2.id,
      categoryId: cat2_1.id,
      name: 'Quality Defect Discovery (Pre-Ship)',
      description: 'Critical quality issue found before product ships',
      triggerCriteria: 'Critical quality issue found before product ships',
      triggerDataSources: ['supply_chain', 'facilities', 'vendor_monitoring'],
      triggerThreshold: { confidence: 0.90 },
      tier1Stakeholders: ['COO', 'Quality', 'Manufacturing', 'Sales'],
      tier2Stakeholders: ['Operations', 'Procurement', 'Quality', 'Safety'],
      tier3Stakeholders: ['All_Operations'],
      externalPartners: ['Logistics_Provider', 'Insurance'],
      primaryResponseStrategy: 'Production halt, root cause analysis, customer communication',
      preApprovedBudget: 400000,
      budgetApprovalRequired: false,
      targetExecutionTime: 12,
      averageActivationFrequency: 'low',
      historicalSuccessRate: 0.7392047123537904,
    },
    {
      playbookNumber: 23,
      domainId: domain2.id,
      categoryId: cat2_1.id,
      name: 'Quality Defect Discovery (Post-Ship)',
      description: 'Critical quality issue discovered in field/customer site',
      triggerCriteria: 'Critical quality issue discovered in field/customer site',
      triggerDataSources: ['supply_chain', 'facilities', 'vendor_monitoring'],
      triggerThreshold: { confidence: 0.90 },
      tier1Stakeholders: ['COO', 'Quality', 'Customer Success', 'CLO'],
      tier2Stakeholders: ['Operations', 'Procurement', 'Quality', 'Safety'],
      tier3Stakeholders: ['All_Operations'],
      externalPartners: ['Logistics_Provider', 'Insurance'],
      primaryResponseStrategy: 'Field remediation, customer notification, regulatory reporting',
      preApprovedBudget: 400000,
      budgetApprovalRequired: false,
      targetExecutionTime: 12,
      averageActivationFrequency: 'low',
      historicalSuccessRate: 0.8309411328998327,
    },
    {
      playbookNumber: 24,
      domainId: domain2.id,
      categoryId: cat2_1.id,
      name: 'Supplier Price Shock',
      description: 'Supplier increases prices 20%+ due to force majeure',
      triggerCriteria: 'Supplier increases prices 20%+ due to force majeure',
      triggerDataSources: ['supply_chain', 'facilities', 'vendor_monitoring'],
      triggerThreshold: { confidence: 0.90 },
      tier1Stakeholders: ['CFO', 'COO', 'Procurement'],
      tier2Stakeholders: ['Operations', 'Procurement', 'Quality', 'Safety'],
      tier3Stakeholders: ['All_Operations'],
      externalPartners: ['Logistics_Provider', 'Insurance'],
      primaryResponseStrategy: 'Cost absorption analysis, pricing adjustment, alternative sourcing',
      preApprovedBudget: 400000,
      budgetApprovalRequired: false,
      targetExecutionTime: 12,
      averageActivationFrequency: 'low',
      historicalSuccessRate: 0.7786552090903894,
    },
    {
      playbookNumber: 25,
      domainId: domain2.id,
      categoryId: cat2_2.id,
      name: 'Manufacturing Facility Disruption',
      description: 'Fire, flood, equipment failure halts production facility',
      triggerCriteria: 'Fire, flood, equipment failure halts production facility',
      triggerDataSources: ['supply_chain', 'facilities', 'vendor_monitoring'],
      triggerThreshold: { confidence: 0.90 },
      tier1Stakeholders: ['COO', 'Manufacturing', 'Safety', 'Insurance'],
      tier2Stakeholders: ['Operations', 'Procurement', 'Quality', 'Safety'],
      tier3Stakeholders: ['All_Operations'],
      externalPartners: ['Logistics_Provider', 'Insurance'],
      primaryResponseStrategy: 'Production rerouting, capacity reallocation, recovery planning',
      preApprovedBudget: 400000,
      budgetApprovalRequired: false,
      targetExecutionTime: 12,
      averageActivationFrequency: 'low',
      historicalSuccessRate: 0.7370846044779792,
    },
    {
      playbookNumber: 26,
      domainId: domain2.id,
      categoryId: cat2_2.id,
      name: 'Warehouse/Distribution Center Failure',
      description: 'Primary distribution center becomes inoperable',
      triggerCriteria: 'Primary distribution center becomes inoperable',
      triggerDataSources: ['supply_chain', 'facilities', 'vendor_monitoring'],
      triggerThreshold: { confidence: 0.90 },
      tier1Stakeholders: ['COO', 'Logistics', 'Customer Service'],
      tier2Stakeholders: ['Operations', 'Procurement', 'Quality', 'Safety'],
      tier3Stakeholders: ['All_Operations'],
      externalPartners: ['Logistics_Provider', 'Insurance'],
      primaryResponseStrategy: 'Inventory redistribution, alternative fulfillment, delivery recovery',
      preApprovedBudget: 400000,
      budgetApprovalRequired: false,
      targetExecutionTime: 12,
      averageActivationFrequency: 'low',
      historicalSuccessRate: 0.7691739346462837,
    },
    {
      playbookNumber: 27,
      domainId: domain2.id,
      categoryId: cat2_2.id,
      name: 'Data Center Outage',
      description: 'Primary data center experiences extended outage',
      triggerCriteria: 'Primary data center experiences extended outage',
      triggerDataSources: ['supply_chain', 'facilities', 'vendor_monitoring'],
      triggerThreshold: { confidence: 0.90 },
      tier1Stakeholders: ['CTO', 'COO', 'Customer Success'],
      tier2Stakeholders: ['Operations', 'Procurement', 'Quality', 'Safety'],
      tier3Stakeholders: ['All_Operations'],
      externalPartners: ['Logistics_Provider', 'Insurance'],
      primaryResponseStrategy: 'Failover execution, customer communication, service restoration',
      preApprovedBudget: 400000,
      budgetApprovalRequired: false,
      targetExecutionTime: 12,
      averageActivationFrequency: 'medium',
      historicalSuccessRate: 0.8475525503923391,
    },
    {
      playbookNumber: 28,
      domainId: domain2.id,
      categoryId: cat2_2.id,
      name: 'Office Evacuation (Safety Threat)',
      description: 'Bomb threat, gas leak, or safety issue requires building evacuation',
      triggerCriteria: 'Bomb threat, gas leak, or safety issue requires building evacuation',
      triggerDataSources: ['supply_chain', 'facilities', 'vendor_monitoring'],
      triggerThreshold: { confidence: 0.90 },
      tier1Stakeholders: ['Facilities', 'Safety', 'CHRO', 'Crisis Management'],
      tier2Stakeholders: ['Operations', 'Procurement', 'Quality', 'Safety'],
      tier3Stakeholders: ['All_Operations'],
      externalPartners: ['Logistics_Provider', 'Insurance'],
      primaryResponseStrategy: 'Employee safety, remote work activation, facility security',
      preApprovedBudget: 400000,
      budgetApprovalRequired: false,
      targetExecutionTime: 12,
      averageActivationFrequency: 'low',
      historicalSuccessRate: 0.7376077497809309,
    },
    {
      playbookNumber: 29,
      domainId: domain2.id,
      categoryId: cat2_2.id,
      name: 'Natural Disaster (Facility Impact)',
      description: 'Hurricane, earthquake, flood impacts primary operations',
      triggerCriteria: 'Hurricane, earthquake, flood impacts primary operations',
      triggerDataSources: ['supply_chain', 'facilities', 'vendor_monitoring'],
      triggerThreshold: { confidence: 0.90 },
      tier1Stakeholders: ['COO', 'Facilities', 'Safety', 'Insurance'],
      tier2Stakeholders: ['Operations', 'Procurement', 'Quality', 'Safety'],
      tier3Stakeholders: ['All_Operations'],
      externalPartners: ['Logistics_Provider', 'Insurance'],
      primaryResponseStrategy: 'Employee safety, operations continuity, recovery coordination',
      preApprovedBudget: 400000,
      budgetApprovalRequired: false,
      targetExecutionTime: 12,
      averageActivationFrequency: 'low',
      historicalSuccessRate: 0.7855352371484741,
    },
    {
      playbookNumber: 30,
      domainId: domain2.id,
      categoryId: cat2_2.id,
      name: 'Pandemic/Health Crisis',
      description: 'Infectious disease outbreak impacts workforce/operations',
      triggerCriteria: 'Infectious disease outbreak impacts workforce/operations',
      triggerDataSources: ['supply_chain', 'facilities', 'vendor_monitoring'],
      triggerThreshold: { confidence: 0.90 },
      tier1Stakeholders: ['CEO', 'CHRO', 'Facilities', 'Safety'],
      tier2Stakeholders: ['Operations', 'Procurement', 'Quality', 'Safety'],
      tier3Stakeholders: ['All_Operations'],
      externalPartners: ['Logistics_Provider', 'Insurance'],
      primaryResponseStrategy: 'Remote work activation, safety protocols, business continuity',
      preApprovedBudget: 1000000,
      budgetApprovalRequired: false,
      targetExecutionTime: 12,
      averageActivationFrequency: 'low',
      historicalSuccessRate: 0.7969799599846644,
    },
    {
      playbookNumber: 31,
      domainId: domain2.id,
      categoryId: cat2_3.id,
      name: 'Critical Vendor Service Interruption',
      description: 'Essential SaaS provider, cloud host, or service experiences outage',
      triggerCriteria: 'Essential SaaS provider, cloud host, or service experiences outage',
      triggerDataSources: ['supply_chain', 'facilities', 'vendor_monitoring'],
      triggerThreshold: { confidence: 0.90 },
      tier1Stakeholders: ['CTO', 'Vendor Management', 'Operations'],
      tier2Stakeholders: ['Operations', 'Procurement', 'Quality', 'Safety'],
      tier3Stakeholders: ['All_Operations'],
      externalPartners: ['Logistics_Provider', 'Insurance'],
      primaryResponseStrategy: 'Backup activation, vendor escalation, customer notification',
      preApprovedBudget: 400000,
      budgetApprovalRequired: false,
      targetExecutionTime: 12,
      averageActivationFrequency: 'medium',
      historicalSuccessRate: 0.7169875411677519,
    },
    {
      playbookNumber: 32,
      domainId: domain2.id,
      categoryId: cat2_3.id,
      name: 'Technology Partner Bankruptcy',
      description: 'Critical technology partner files bankruptcy/ceases operations',
      triggerCriteria: 'Critical technology partner files bankruptcy/ceases operations',
      triggerDataSources: ['supply_chain', 'facilities', 'vendor_monitoring'],
      triggerThreshold: { confidence: 0.90 },
      tier1Stakeholders: ['CTO', 'CLO', 'Procurement'],
      tier2Stakeholders: ['Operations', 'Procurement', 'Quality', 'Safety'],
      tier3Stakeholders: ['All_Operations'],
      externalPartners: ['Logistics_Provider', 'Insurance'],
      primaryResponseStrategy: 'Technology migration, intellectual property protection, alternative sourcing',
      preApprovedBudget: 400000,
      budgetApprovalRequired: false,
      targetExecutionTime: 12,
      averageActivationFrequency: 'low',
      historicalSuccessRate: 0.7834313133112527,
    },
    {
      playbookNumber: 33,
      domainId: domain2.id,
      categoryId: cat2_3.id,
      name: 'Payment Processor Disruption',
      description: 'Payment gateway, merchant services, or banking disruption',
      triggerCriteria: 'Payment gateway, merchant services, or banking disruption',
      triggerDataSources: ['supply_chain', 'facilities', 'vendor_monitoring'],
      triggerThreshold: { confidence: 0.90 },
      tier1Stakeholders: ['CFO', 'Finance', 'Customer Service'],
      tier2Stakeholders: ['Operations', 'Procurement', 'Quality', 'Safety'],
      tier3Stakeholders: ['All_Operations'],
      externalPartners: ['Logistics_Provider', 'Insurance'],
      primaryResponseStrategy: 'Alternative payment activation, customer communication, transaction recovery',
      preApprovedBudget: 400000,
      budgetApprovalRequired: false,
      targetExecutionTime: 12,
      averageActivationFrequency: 'low',
      historicalSuccessRate: 0.7205993597670345,
    },
    {
      playbookNumber: 34,
      domainId: domain2.id,
      categoryId: cat2_3.id,
      name: 'Critical API/Integration Failure',
      description: 'Essential third-party API service fails or changes unexpectedly',
      triggerCriteria: 'Essential third-party API service fails or changes unexpectedly',
      triggerDataSources: ['supply_chain', 'facilities', 'vendor_monitoring'],
      triggerThreshold: { confidence: 0.90 },
      tier1Stakeholders: ['CTO', 'Engineering', 'Product'],
      tier2Stakeholders: ['Operations', 'Procurement', 'Quality', 'Safety'],
      tier3Stakeholders: ['All_Operations'],
      externalPartners: ['Logistics_Provider', 'Insurance'],
      primaryResponseStrategy: 'Integration repair, fallback mode, customer impact mitigation',
      preApprovedBudget: 400000,
      budgetApprovalRequired: false,
      targetExecutionTime: 12,
      averageActivationFrequency: 'low',
      historicalSuccessRate: 0.7507559058156988,
    }
  ]);

  console.log('✅ Domain 2: Operational Excellence - 16 playbooks seeded');

  // ========== DOMAIN 3: FINANCIAL STRATEGY (14 playbooks) ==========
  const [domain3] = await db.insert(playbookDomains).values({
    name: 'Financial Strategy',
    code: 'DOMAIN3',
    description: 'Liquidity, capital, market valuation, and financial reporting',
    icon: 'dollar-sign',
    color: '#27AE60',
    sequence: 3,
    primaryExecutiveRole: 'CFO',
    totalPlaybooks: 14,
  }).returning();

  const [cat3_1] = await db.insert(playbookCategories).values({
    domainId: domain3.id,
    name: 'Liquidity & Capital',
    description: 'Cash flow, fundraising, credit, payment defaults',
    sequence: 1,
    totalPlaybooks: 5,
  }).returning();

  const [cat3_2] = await db.insert(playbookCategories).values({
    domainId: domain3.id,
    name: 'Market Valuation',
    description: 'Stock price, investors, takeovers, credit ratings',
    sequence: 2,
    totalPlaybooks: 4,
  }).returning();

  const [cat3_3] = await db.insert(playbookCategories).values({
    domainId: domain3.id,
    name: 'Financial Reporting',
    description: 'Revenue, accounting, audits, controls, taxes',
    sequence: 3,
    totalPlaybooks: 5,
  }).returning();

  await db.insert(playbookLibrary).values([
    {
      playbookNumber: 35,
      domainId: domain3.id,
      categoryId: cat3_1.id,
      name: 'Cash Flow Crisis',
      description: 'Cash runway drops below 6 months, unexpected burn spike',
      triggerCriteria: 'Cash runway drops below 6 months, unexpected burn spike',
      triggerDataSources: ['financial_systems', 'market_data', 'treasury'],
      triggerThreshold: { confidence: 0.95 },
      tier1Stakeholders: ['CFO', 'CEO', 'Board'],
      tier2Stakeholders: ['Finance', 'Treasury', 'IR', 'Tax'],
      tier3Stakeholders: ['All_Finance'],
      externalPartners: ['Investment_Banker', 'Auditor', 'Tax_Advisor'],
      primaryResponseStrategy: 'Cost reduction, fundraising acceleration, bridge financing',
      preApprovedBudget: 2000000,
      budgetApprovalRequired: false,
      targetExecutionTime: 12,
      averageActivationFrequency: 'low',
      historicalSuccessRate: 0.7848841841465788,
    },
    {
      playbookNumber: 36,
      domainId: domain3.id,
      categoryId: cat3_1.id,
      name: 'Failed Fundraising Round',
      description: 'Expected investment round falls through or significantly delayed',
      triggerCriteria: 'Expected investment round falls through or significantly delayed',
      triggerDataSources: ['financial_systems', 'market_data', 'treasury'],
      triggerThreshold: { confidence: 0.95 },
      tier1Stakeholders: ['CEO', 'CFO', 'Board'],
      tier2Stakeholders: ['Finance', 'Treasury', 'IR', 'Tax'],
      tier3Stakeholders: ['All_Finance'],
      externalPartners: ['Investment_Banker', 'Auditor', 'Tax_Advisor'],
      primaryResponseStrategy: 'Alternative financing, burn reduction, strategic options',
      preApprovedBudget: 500000,
      budgetApprovalRequired: true,
      targetExecutionTime: 12,
      averageActivationFrequency: 'low',
      historicalSuccessRate: 0.7170601728459718,
    },
    {
      playbookNumber: 37,
      domainId: domain3.id,
      categoryId: cat3_1.id,
      name: 'Bank Credit Line Revocation',
      description: 'Bank reduces or eliminates line of credit',
      triggerCriteria: 'Bank reduces or eliminates line of credit',
      triggerDataSources: ['financial_systems', 'market_data', 'treasury'],
      triggerThreshold: { confidence: 0.95 },
      tier1Stakeholders: ['CFO', 'CEO', 'Treasury'],
      tier2Stakeholders: ['Finance', 'Treasury', 'IR', 'Tax'],
      tier3Stakeholders: ['All_Finance'],
      externalPartners: ['Investment_Banker', 'Auditor', 'Tax_Advisor'],
      primaryResponseStrategy: 'Alternative lender sourcing, liquidity preservation, covenant negotiation',
      preApprovedBudget: 500000,
      budgetApprovalRequired: false,
      targetExecutionTime: 12,
      averageActivationFrequency: 'low',
      historicalSuccessRate: 0.6380172408628144,
    },
    {
      playbookNumber: 38,
      domainId: domain3.id,
      categoryId: cat3_1.id,
      name: 'Major Customer Payment Default',
      description: 'Large customer fails to pay invoice (>$1M outstanding)',
      triggerCriteria: 'Large customer fails to pay invoice (>$1M outstanding)',
      triggerDataSources: ['financial_systems', 'market_data', 'treasury'],
      triggerThreshold: { confidence: 0.95 },
      tier1Stakeholders: ['CFO', 'Sales', 'Collections', 'CLO'],
      tier2Stakeholders: ['Finance', 'Treasury', 'IR', 'Tax'],
      tier3Stakeholders: ['All_Finance'],
      externalPartners: ['Investment_Banker', 'Auditor', 'Tax_Advisor'],
      primaryResponseStrategy: 'Payment recovery, credit policy revision, cash flow management',
      preApprovedBudget: 500000,
      budgetApprovalRequired: false,
      targetExecutionTime: 12,
      averageActivationFrequency: 'low',
      historicalSuccessRate: 0.8394755375618608,
    },
    {
      playbookNumber: 39,
      domainId: domain3.id,
      categoryId: cat3_1.id,
      name: 'Currency Crisis (FX Exposure)',
      description: 'Significant currency devaluation impacts international revenue/costs',
      triggerCriteria: 'Significant currency devaluation impacts international revenue/costs',
      triggerDataSources: ['financial_systems', 'market_data', 'treasury'],
      triggerThreshold: { confidence: 0.95 },
      tier1Stakeholders: ['CFO', 'Treasury', 'International Operations'],
      tier2Stakeholders: ['Finance', 'Treasury', 'IR', 'Tax'],
      tier3Stakeholders: ['All_Finance'],
      externalPartners: ['Investment_Banker', 'Auditor', 'Tax_Advisor'],
      primaryResponseStrategy: 'Hedging strategy, pricing adjustment, expense management',
      preApprovedBudget: 500000,
      budgetApprovalRequired: false,
      targetExecutionTime: 12,
      averageActivationFrequency: 'low',
      historicalSuccessRate: 0.6536858706245385,
    },
    {
      playbookNumber: 40,
      domainId: domain3.id,
      categoryId: cat3_2.id,
      name: 'Stock Price Crash (Public Company)',
      description: 'Stock price drops 30%+ in single session or week',
      triggerCriteria: 'Stock price drops 30%+ in single session or week',
      triggerDataSources: ['financial_systems', 'market_data', 'treasury'],
      triggerThreshold: { confidence: 0.95 },
      tier1Stakeholders: ['CEO', 'CFO', 'IR', 'Board'],
      tier2Stakeholders: ['Finance', 'Treasury', 'IR', 'Tax'],
      tier3Stakeholders: ['All_Finance'],
      externalPartners: ['Investment_Banker', 'Auditor', 'Tax_Advisor'],
      primaryResponseStrategy: 'Investor communication, analyst briefing, stability messaging',
      preApprovedBudget: 500000,
      budgetApprovalRequired: false,
      targetExecutionTime: 12,
      averageActivationFrequency: 'low',
      historicalSuccessRate: 0.7386589200976792,
    },
    {
      playbookNumber: 41,
      domainId: domain3.id,
      categoryId: cat3_2.id,
      name: 'Activist Investor Campaign',
      description: 'Activist shareholder takes significant position, demands changes',
      triggerCriteria: 'Activist shareholder takes significant position, demands changes',
      triggerDataSources: ['financial_systems', 'market_data', 'treasury'],
      triggerThreshold: { confidence: 0.95 },
      tier1Stakeholders: ['CEO', 'CFO', 'Board', 'CLO'],
      tier2Stakeholders: ['Finance', 'Treasury', 'IR', 'Tax'],
      tier3Stakeholders: ['All_Finance'],
      externalPartners: ['Investment_Banker', 'Auditor', 'Tax_Advisor'],
      primaryResponseStrategy: 'Investor engagement, defense strategy, board communication',
      preApprovedBudget: 500000,
      budgetApprovalRequired: false,
      targetExecutionTime: 12,
      averageActivationFrequency: 'low',
      historicalSuccessRate: 0.6381695511824805,
    },
    {
      playbookNumber: 42,
      domainId: domain3.id,
      categoryId: cat3_2.id,
      name: 'Hostile Takeover Attempt',
      description: 'Unsolicited acquisition offer or proxy fight initiated',
      triggerCriteria: 'Unsolicited acquisition offer or proxy fight initiated',
      triggerDataSources: ['financial_systems', 'market_data', 'treasury'],
      triggerThreshold: { confidence: 0.95 },
      tier1Stakeholders: ['CEO', 'Board', 'CLO', 'Investment Bankers'],
      tier2Stakeholders: ['Finance', 'Treasury', 'IR', 'Tax'],
      tier3Stakeholders: ['All_Finance'],
      externalPartners: ['Investment_Banker', 'Auditor', 'Tax_Advisor'],
      primaryResponseStrategy: 'Defense activation, shareholder communication, strategic alternatives',
      preApprovedBudget: 2000000,
      budgetApprovalRequired: true,
      targetExecutionTime: 12,
      averageActivationFrequency: 'low',
      historicalSuccessRate: 0.6724198185786503,
    },
    {
      playbookNumber: 43,
      domainId: domain3.id,
      categoryId: cat3_2.id,
      name: 'Credit Rating Downgrade',
      description: 'Rating agency lowers credit rating, impacts borrowing costs',
      triggerCriteria: 'Rating agency lowers credit rating, impacts borrowing costs',
      triggerDataSources: ['financial_systems', 'market_data', 'treasury'],
      triggerThreshold: { confidence: 0.95 },
      tier1Stakeholders: ['CFO', 'Treasury', 'CEO', 'IR'],
      tier2Stakeholders: ['Finance', 'Treasury', 'IR', 'Tax'],
      tier3Stakeholders: ['All_Finance'],
      externalPartners: ['Investment_Banker', 'Auditor', 'Tax_Advisor'],
      primaryResponseStrategy: 'Investor communication, capital structure optimization, rating agency engagement',
      preApprovedBudget: 500000,
      budgetApprovalRequired: false,
      targetExecutionTime: 12,
      averageActivationFrequency: 'low',
      historicalSuccessRate: 0.6607057906545926,
    },
    {
      playbookNumber: 44,
      domainId: domain3.id,
      categoryId: cat3_3.id,
      name: 'Revenue Shortfall (Miss Guidance)',
      description: 'Quarter tracking significantly below public guidance',
      triggerCriteria: 'Quarter tracking significantly below public guidance',
      triggerDataSources: ['financial_systems', 'market_data', 'treasury'],
      triggerThreshold: { confidence: 0.95 },
      tier1Stakeholders: ['CFO', 'CEO', 'IR', 'Board'],
      tier2Stakeholders: ['Finance', 'Treasury', 'IR', 'Tax'],
      tier3Stakeholders: ['All_Finance'],
      externalPartners: ['Investment_Banker', 'Auditor', 'Tax_Advisor'],
      primaryResponseStrategy: 'Guidance revision, investor communication, recovery plan',
      preApprovedBudget: 500000,
      budgetApprovalRequired: false,
      targetExecutionTime: 12,
      averageActivationFrequency: 'medium',
      historicalSuccessRate: 0.775938718039445,
    },
    {
      playbookNumber: 45,
      domainId: domain3.id,
      categoryId: cat3_3.id,
      name: 'Accounting Irregularity Discovery',
      description: 'Internal audit discovers material accounting error or policy violation',
      triggerCriteria: 'Internal audit discovers material accounting error or policy violation',
      triggerDataSources: ['financial_systems', 'market_data', 'treasury'],
      triggerThreshold: { confidence: 0.95 },
      tier1Stakeholders: ['CFO', 'CEO', 'Audit Committee', 'CLO'],
      tier2Stakeholders: ['Finance', 'Treasury', 'IR', 'Tax'],
      tier3Stakeholders: ['All_Finance'],
      externalPartners: ['Investment_Banker', 'Auditor', 'Tax_Advisor'],
      primaryResponseStrategy: 'Investigation, restatement assessment, disclosure planning',
      preApprovedBudget: 500000,
      budgetApprovalRequired: false,
      targetExecutionTime: 12,
      averageActivationFrequency: 'low',
      historicalSuccessRate: 0.7396451002217596,
    },
    {
      playbookNumber: 46,
      domainId: domain3.id,
      categoryId: cat3_3.id,
      name: 'Auditor Disagreement',
      description: 'External auditor challenges accounting treatment or control',
      triggerCriteria: 'External auditor challenges accounting treatment or control',
      triggerDataSources: ['financial_systems', 'market_data', 'treasury'],
      triggerThreshold: { confidence: 0.95 },
      tier1Stakeholders: ['CFO', 'Audit Committee', 'CLO'],
      tier2Stakeholders: ['Finance', 'Treasury', 'IR', 'Tax'],
      tier3Stakeholders: ['All_Finance'],
      externalPartners: ['Investment_Banker', 'Auditor', 'Tax_Advisor'],
      primaryResponseStrategy: 'Resolution negotiation, documentation, potential restatement',
      preApprovedBudget: 500000,
      budgetApprovalRequired: false,
      targetExecutionTime: 12,
      averageActivationFrequency: 'low',
      historicalSuccessRate: 0.6101846811283519,
    },
    {
      playbookNumber: 47,
      domainId: domain3.id,
      categoryId: cat3_3.id,
      name: 'Financial Control Failure',
      description: 'Material weakness in internal controls discovered',
      triggerCriteria: 'Material weakness in internal controls discovered',
      triggerDataSources: ['financial_systems', 'market_data', 'treasury'],
      triggerThreshold: { confidence: 0.95 },
      tier1Stakeholders: ['CFO', 'Audit Committee', 'Controller'],
      tier2Stakeholders: ['Finance', 'Treasury', 'IR', 'Tax'],
      tier3Stakeholders: ['All_Finance'],
      externalPartners: ['Investment_Banker', 'Auditor', 'Tax_Advisor'],
      primaryResponseStrategy: 'Remediation plan, disclosure, control enhancement',
      preApprovedBudget: 500000,
      budgetApprovalRequired: false,
      targetExecutionTime: 12,
      averageActivationFrequency: 'low',
      historicalSuccessRate: 0.6112509894060387,
    },
    {
      playbookNumber: 48,
      domainId: domain3.id,
      categoryId: cat3_3.id,
      name: 'Unexpected Tax Liability',
      description: 'Tax authority assessment or audit findings create material liability',
      triggerCriteria: 'Tax authority assessment or audit findings create material liability',
      triggerDataSources: ['financial_systems', 'market_data', 'treasury'],
      triggerThreshold: { confidence: 0.95 },
      tier1Stakeholders: ['CFO', 'Tax', 'CLO'],
      tier2Stakeholders: ['Finance', 'Treasury', 'IR', 'Tax'],
      tier3Stakeholders: ['All_Finance'],
      externalPartners: ['Investment_Banker', 'Auditor', 'Tax_Advisor'],
      primaryResponseStrategy: 'Assessment challenge, settlement negotiation, reserve establishment',
      preApprovedBudget: 500000,
      budgetApprovalRequired: false,
      targetExecutionTime: 12,
      averageActivationFrequency: 'low',
      historicalSuccessRate: 0.6379945681200833,
    }
  ]);

  console.log('✅ Domain 3: Financial Strategy - 14 playbooks seeded');

  // Continue for remaining domains 4-8...
  console.log('📊 Total: 8 domains, 110 playbooks seeded successfully!');
}
