// Unified Demo Scenario Configuration for all 7 Live Demos
// All demos now use the same DemoLiveActivation component with different scenario data

export interface DemoScenario {
  id: string;
  title: string;
  playbook: string;
  description: string;
  emoji: string;
  tasks: TaskEvent[];
  stakeholderRoster: StakeholderInfo[];
  targetCompletionTime: number;
  beforeMetrics: {
    time: string;
    cost: string;
    overhead: string;
  };
  afterMetrics: {
    time: string;
    cost: string;
    overhead: string;
  };
  valueProp: string;
  timeMultiplier: string;
}

export interface TaskEvent {
  id: string;
  time: number;
  type: 'task' | 'system' | 'milestone';
  title: string;
  description: string;
}

export interface StakeholderInfo {
  id: number;
  name: string;
  role: string;
  department: string;
  priority: 'Critical' | 'High' | 'Medium' | 'Low';
  region?: string;
}

export const DEMO_SCENARIOS: Record<string, DemoScenario> = {
  ransomware: {
    id: 'ransomware',
    title: "Ransomware Response: System Breach Detected",
    playbook: "Critical Incident Response - Ransomware Attack",
    description: "AWS CloudWatch detected unusual encryption activity across production servers. Auto-triggering coordinated response.",
    emoji: "🛡️",
    targetCompletionTime: 707,
    tasks: [
      { id: 't1', time: 30, type: 'system', title: 'ServiceNow Ticket Auto-Created', description: 'INC-2024-47291 - Critical: Ransomware Detection' },
      { id: 't2', time: 45, type: 'system', title: 'Slack War Room Initiated', description: '#incident-ransomware-2024-11 created with 30 stakeholders' },
      { id: 't3', time: 60, type: 'milestone', title: 'First Stakeholder Acknowledged', description: 'CFO Sarah Chen responded in 47 seconds' },
      { id: 't4', time: 90, type: 'task', title: 'Isolating Affected Systems', description: 'IT Security locking down network segment 10.x.x.x' },
      { id: 't5', time: 135, type: 'system', title: 'AWS Resources Locked', description: 'Auto-triggered: S3 buckets moved to compliance hold' },
      { id: 't6', time: 180, type: 'task', title: 'Legal Review Initiated', description: 'CLO reviewing breach notification requirements' },
      { id: 't7', time: 240, type: 'milestone', title: '50% Coordination Reached', description: '15 of 30 executives acknowledged and briefed' },
      { id: 't8', time: 300, type: 'task', title: 'Incident Response Team Assembled', description: 'All key stakeholders in Slack war room' },
      { id: 't9', time: 360, type: 'system', title: 'Backup Systems Verified', description: 'Offline backups confirmed clean - recovery possible' },
      { id: 't10', time: 420, type: 'task', title: 'PR Response Prepared', description: 'CMO drafting customer communication' },
      { id: 't11', time: 480, type: 'system', title: 'Forensics Initiated', description: 'Security team analyzing attack vector' },
      { id: 't12', time: 540, type: 'milestone', title: '70% Coordination Reached', description: '21 of 30 executives acknowledged' },
      { id: 't13', time: 600, type: 'task', title: 'Recovery Plan Approved', description: '$150K emergency budget authorized by CFO' },
      { id: 't14', time: 660, type: 'system', title: 'Compliance Notifications Queued', description: 'SEC & regulatory filings prepared' },
      { id: 't15', time: 684, type: 'milestone', title: '80% COORDINATION COMPLETE', description: '24 of 30 executives acknowledged - threshold met!' },
      { id: 't16', time: 707, type: 'milestone', title: 'FULL COORDINATION ACHIEVED', description: '28 of 30 stakeholders coordinated - execution complete!' },
    ],
    stakeholderRoster: [
      { id: 1, name: 'Sarah Chen', role: 'CFO', department: 'Finance', priority: 'Critical' },
      { id: 2, name: 'Michael Rodriguez', role: 'CTO', department: 'Technology', priority: 'Critical' },
      { id: 3, name: 'Jennifer Park', role: 'CEO', department: 'Executive', priority: 'Critical' },
      { id: 4, name: 'David Wilson', role: 'COO', department: 'Operations', priority: 'Critical' },
      { id: 5, name: 'Emily Taylor', role: 'Chief Legal Officer', department: 'Legal', priority: 'Critical' },
      { id: 6, name: 'Robert Kim', role: 'CISO', department: 'Security', priority: 'Critical' },
      { id: 7, name: 'Lisa Anderson', role: 'CMO', department: 'Marketing', priority: 'High' },
      { id: 8, name: 'James Martinez', role: 'VP of Engineering', department: 'Technology', priority: 'Critical' },
      { id: 9, name: 'Maria Garcia', role: 'VP of Operations', department: 'Operations', priority: 'High' },
      { id: 10, name: 'Thomas Brown', role: 'VP of Finance', department: 'Finance', priority: 'High' },
      { id: 11, name: 'Susan Lee', role: 'Director of IT', department: 'Technology', priority: 'Critical' },
      { id: 12, name: 'Christopher White', role: 'Director of Security', department: 'Security', priority: 'Critical' },
      { id: 13, name: 'Jessica Thompson', role: 'Director of Compliance', department: 'Legal', priority: 'High' },
      { id: 14, name: 'Daniel Moore', role: 'Director of PR', department: 'Marketing', priority: 'High' },
      { id: 15, name: 'Amanda Jackson', role: 'VP of Customer Success', department: 'Customer', priority: 'High' },
      { id: 16, name: 'Ryan Davis', role: 'VP of Sales', department: 'Sales', priority: 'Medium' },
      { id: 17, name: 'Michelle Harris', role: 'Director of HR', department: 'Human Resources', priority: 'Medium' },
      { id: 18, name: 'Kevin Clark', role: 'Director of Risk', department: 'Risk Management', priority: 'High' },
      { id: 19, name: 'Laura Lewis', role: 'VP of Product', department: 'Product', priority: 'Medium' },
      { id: 20, name: 'Brian Walker', role: 'Director of Infrastructure', department: 'Technology', priority: 'Critical' },
      { id: 21, name: 'Nicole Hall', role: 'Director of Data', department: 'Technology', priority: 'High' },
      { id: 22, name: 'Steven Allen', role: 'VP of Corporate Dev', department: 'Strategy', priority: 'Medium' },
      { id: 23, name: 'Rachel Young', role: 'Director of Communications', department: 'Marketing', priority: 'High' },
      { id: 24, name: 'Andrew King', role: 'Director of Legal Affairs', department: 'Legal', priority: 'High' },
      { id: 25, name: 'Patricia Wright', role: 'VP of Strategy', department: 'Strategy', priority: 'Medium' },
      { id: 26, name: 'Eric Green', role: 'Director of Audit', department: 'Finance', priority: 'High' },
      { id: 27, name: 'Samantha Scott', role: 'Director of Facilities', department: 'Operations', priority: 'Medium' },
      { id: 28, name: 'Gregory Adams', role: 'VP of Investor Relations', department: 'Finance', priority: 'Medium' },
      { id: 29, name: 'Angela Baker', role: 'Director of Analytics', department: 'Technology', priority: 'Medium' },
      { id: 30, name: 'Mark Nelson', role: 'Director of Business Continuity', department: 'Risk Management', priority: 'High' },
    ],
    beforeMetrics: {
      time: "48-72h",
      cost: "$433K",
      overhead: "Manual coordination chaos"
    },
    afterMetrics: {
      time: "11:47 min",
      cost: "$150K",
      overhead: "Automated orchestration"
    },
    valueProp: "$283K saved",
    timeMultiplier: "240x faster"
  },

  'ma-integration': {
    id: 'ma-integration',
    title: "M&A Integration - CloudTech Acquisition",
    playbook: "M&A Integration - 100 Day Plan",
    description: "Just closed $500M acquisition of CloudTech. 100-day integration plan must begin immediately. Coordinating 45 stakeholders across both companies for Day 1 execution.",
    emoji: "🤝",
    targetCompletionTime: 707,
    tasks: [
      { id: 't1', time: 0, type: 'milestone', title: 'Integration Playbook Activated', description: 'CEO triggered M&A integration coordination' },
      { id: 't2', time: 15, type: 'system', title: 'Email Sent to 45 Stakeholders', description: 'All integration team members notified' },
      { id: 't3', time: 30, type: 'system', title: 'Slack Notifications Distributed', description: 'Integration war room channels created' },
      { id: 't4', time: 60, type: 'task', title: 'CEO (Acquiring) Acknowledged', description: 'Leadership aligned on Day 1 priorities' },
      { id: 't5', time: 80, type: 'task', title: 'General Counsel Acknowledged', description: 'Legal integration checklist confirmed' },
      { id: 't6', time: 105, type: 'task', title: 'CFO (Acquiring) Acknowledged', description: 'Financial systems integration approved' },
      { id: 't7', time: 130, type: 'task', title: 'Head of Corp Dev Acknowledged', description: 'Deal structure communication ready' },
      { id: 't8', time: 150, type: 'milestone', title: '8 Tier 1 Stakeholders Coordinated', description: 'All decision makers aligned' },
      { id: 't9', time: 180, type: 'system', title: 'Integration War Room URL Shared', description: 'Central command center established' },
      { id: 't10', time: 210, type: 'task', title: 'CTO (Acquiring) Acknowledged', description: 'Technology integration roadmap confirmed' },
      { id: 't11', time: 240, type: 'task', title: 'CHRO (Both) Acknowledged', description: 'HR integration and retention plans active' },
      { id: 't12', time: 285, type: 'milestone', title: 'VP Operations Teams Coordinated', description: 'Operations integration underway' },
      { id: 't13', time: 330, type: 'system', title: 'Day 1 Task List Distributed', description: 'All teams have execution plans' },
      { id: 't14', time: 360, type: 'milestone', title: '15 Stakeholders Acknowledged', description: 'Core team ready for execution' },
      { id: 't15', time: 390, type: 'task', title: 'Financial Systems Integration Team Ready', description: 'Accounting and reporting alignment confirmed' },
      { id: 't16', time: 420, type: 'task', title: 'IT Integration Team Ready', description: 'Infrastructure and security integration planned' },
      { id: 't17', time: 465, type: 'milestone', title: '20 Stakeholders Acknowledged', description: 'Functional leads coordinated' },
      { id: 't18', time: 480, type: 'task', title: 'HR Integration Team Ready', description: 'Benefits, payroll, and culture integration active' },
      { id: 't19', time: 510, type: 'task', title: 'Sales Team Coordination Complete', description: 'Combined sales teams aligned on targets' },
      { id: 't20', time: 540, type: 'milestone', title: '25 Stakeholders Acknowledged', description: 'Majority of integration team ready' },
      { id: 't21', time: 585, type: 'task', title: 'Customer Success Handoff Plan Active', description: 'Customer retention strategy deployed' },
      { id: 't22', time: 600, type: 'milestone', title: '30 Stakeholders Acknowledged', description: 'Two-thirds coordination achieved' },
      { id: 't23', time: 630, type: 'system', title: 'Legal Integration Checklist Shared', description: 'Compliance and regulatory requirements distributed' },
      { id: 't24', time: 650, type: 'milestone', title: '80% COORDINATION COMPLETE', description: '36 of 45 stakeholders acknowledged - threshold met!' },
      { id: 't25', time: 675, type: 'task', title: 'Product Roadmap Alignment Complete', description: 'Combined product strategy confirmed' },
      { id: 't26', time: 707, type: 'milestone', title: 'ALL CRITICAL STAKEHOLDERS COORDINATED', description: '42 of 45 stakeholders ready for Day 1 execution!' },
    ],
    stakeholderRoster: [
      { id: 1, name: 'Jennifer Park', role: 'CEO (Acquiring)', department: 'Executive', priority: 'Critical' },
      { id: 2, name: 'Marcus Chen', role: 'CFO (Acquiring)', department: 'Finance', priority: 'Critical' },
      { id: 3, name: 'Samantha Brooks', role: 'General Counsel', department: 'Legal', priority: 'Critical' },
      { id: 4, name: 'David Martinez', role: 'CTO (Acquiring)', department: 'Technology', priority: 'Critical' },
      { id: 5, name: 'Rachel Morrison', role: 'CHRO (Acquiring)', department: 'HR', priority: 'Critical' },
      { id: 6, name: 'James Sullivan', role: 'Head of Corp Dev', department: 'Corporate Development', priority: 'Critical' },
      { id: 7, name: 'Patricia Young', role: 'COO (Acquiring)', department: 'Operations', priority: 'Critical' },
      { id: 8, name: 'Robert Chang', role: 'Chief Strategy Officer', department: 'Strategy', priority: 'Critical' },
      { id: 9, name: 'Alex Thompson', role: 'CEO (CloudTech)', department: 'Executive', priority: 'Critical' },
      { id: 10, name: 'Emily Rodriguez', role: 'CFO (CloudTech)', department: 'Finance', priority: 'Critical' },
      { id: 11, name: 'Michael Kim', role: 'CTO (CloudTech)', department: 'Technology', priority: 'Critical' },
      { id: 12, name: 'Sarah Williams', role: 'CHRO (CloudTech)', department: 'HR', priority: 'Critical' },
      { id: 13, name: 'Daniel Foster', role: 'VP Product (CloudTech)', department: 'Product', priority: 'High' },
      { id: 14, name: 'Catherine Lee', role: 'Integration Director', department: 'Integration PMO', priority: 'Critical' },
      { id: 15, name: 'Thomas Anderson', role: 'Integration Finance Lead', department: 'Finance', priority: 'High' },
      { id: 16, name: 'Michelle Carter', role: 'Integration Tech Lead', department: 'Technology', priority: 'High' },
      { id: 17, name: 'Christopher Walsh', role: 'Integration HR Lead', department: 'HR', priority: 'High' },
      { id: 18, name: 'Victoria Santos', role: 'Integration Legal Lead', department: 'Legal', priority: 'High' },
      { id: 19, name: 'Brian Mitchell', role: 'VP Finance (Acquiring)', department: 'Finance', priority: 'High' },
      { id: 20, name: 'Laura Garcia', role: 'Controller (Acquiring)', department: 'Finance', priority: 'High' },
      { id: 21, name: 'Kevin Wright', role: 'Controller (CloudTech)', department: 'Finance', priority: 'High' },
      { id: 22, name: 'Amanda Hughes', role: 'Director of FP&A', department: 'Finance', priority: 'Medium' },
      { id: 23, name: 'Steven Clark', role: 'VP Engineering (Acquiring)', department: 'Technology', priority: 'High' },
      { id: 24, name: 'Nicole Rivera', role: 'VP Engineering (CloudTech)', department: 'Technology', priority: 'High' },
      { id: 25, name: 'Gregory Taylor', role: 'Director of IT (Acquiring)', department: 'Technology', priority: 'High' },
      { id: 26, name: 'Jessica Moore', role: 'Director of IT (CloudTech)', department: 'Technology', priority: 'High' },
      { id: 27, name: 'Andrew Baker', role: 'Director of InfoSec', department: 'Security', priority: 'High' },
      { id: 28, name: 'Lisa Thompson', role: 'VP Total Rewards', department: 'HR', priority: 'Medium' },
      { id: 29, name: 'Richard Davis', role: 'Director of Talent', department: 'HR', priority: 'Medium' },
      { id: 30, name: 'Maria Gonzalez', role: 'Director of Culture', department: 'HR', priority: 'Medium' },
      { id: 31, name: 'Daniel Phillips', role: 'VP Sales (Acquiring)', department: 'Sales', priority: 'High' },
      { id: 32, name: 'Olivia Brown', role: 'VP Sales (CloudTech)', department: 'Sales', priority: 'High' },
      { id: 33, name: 'Matthew Collins', role: 'VP Customer Success (Acquiring)', department: 'Customer Success', priority: 'High' },
      { id: 34, name: 'Sophia Turner', role: 'VP Customer Success (CloudTech)', department: 'Customer Success', priority: 'High' },
      { id: 35, name: 'William Evans', role: 'Director of Communications', department: 'Communications', priority: 'Medium' },
      { id: 36, name: 'Isabella Murphy', role: 'VP Product (Acquiring)', department: 'Product', priority: 'High' },
      { id: 37, name: 'Noah Stewart', role: 'Director of Product Operations', department: 'Product', priority: 'Medium' },
      { id: 38, name: 'Emma Reed', role: 'Director of Business Integration', department: 'Integration PMO', priority: 'High' },
      { id: 39, name: 'Lucas Hayes', role: 'Director of Systems Integration', department: 'Technology', priority: 'High' },
      { id: 40, name: 'Ava Bennett', role: 'Director of Cultural Integration', department: 'HR', priority: 'Medium' },
      { id: 41, name: 'Ethan Cooper', role: 'VP Operations (Acquiring)', department: 'Operations', priority: 'High' },
      { id: 42, name: 'Mia Richardson', role: 'VP Operations (CloudTech)', department: 'Operations', priority: 'High' },
      { id: 43, name: 'Benjamin Price', role: 'Director of Facilities Integration', department: 'Operations', priority: 'Low' },
      { id: 44, name: 'Charlotte Howard', role: 'Director of Vendor Management', department: 'Procurement', priority: 'Medium' },
      { id: 45, name: 'Henry Ward', role: 'Director of Synergy Realization', department: 'Integration PMO', priority: 'High' },
    ],
    beforeMetrics: {
      time: "3-5 days",
      cost: "$875K",
      overhead: "Email chains, scattered coordination"
    },
    afterMetrics: {
      time: "11:47 min",
      cost: "$125K",
      overhead: "Automated playbook execution"
    },
    valueProp: "$750K saved",
    timeMultiplier: "360x faster"
  },

  'product-launch': {
    id: 'product-launch',
    title: "Global Product Launch - NexGen Platform",
    playbook: "Multi-Country Product Launch - 15 Markets",
    description: "Launching NexGen Platform across 15 countries simultaneously. Coordinating 50 stakeholders across regions, functions, and time zones for synchronized go-to-market.",
    emoji: "🚀",
    targetCompletionTime: 707,
    tasks: [
      { id: 't1', time: 0, type: 'milestone', title: 'Global Launch Playbook Activated', description: 'CEO triggered worldwide product launch coordination' },
      { id: 't2', time: 15, type: 'system', title: '50 Stakeholders Notified Across 12 Time Zones', description: 'Global team mobilized for synchronized launch' },
      { id: 't3', time: 45, type: 'task', title: 'CEO Acknowledged: "All Systems Go"', description: 'Executive leadership committed to launch timeline' },
      { id: 't4', time: 70, type: 'task', title: 'CMO Acknowledged', description: 'Global marketing campaign ready' },
      { id: 't5', time: 90, type: 'task', title: 'CPO Acknowledged', description: 'Product readiness confirmed across all markets' },
      { id: 't6', time: 120, type: 'milestone', title: 'C-Suite Aligned (7/7 = 100%)', description: 'All executive stakeholders committed' },
      { id: 't7', time: 150, type: 'task', title: 'North America GM Acknowledged', description: 'US and Canada markets ready' },
      { id: 't8', time: 180, type: 'milestone', title: 'Europe GMs Coordinated (3/3)', description: 'UK, DACH, and Southern Europe aligned' },
      { id: 't9', time: 225, type: 'system', title: 'Launch War Room Activated', description: 'Global command center established' },
      { id: 't10', time: 255, type: 'milestone', title: 'APAC GMs Acknowledged (4/4)', description: 'Japan, China, India, Southeast Asia ready' },
      { id: 't11', time: 285, type: 'milestone', title: '15 Regional GMs Coordinated', description: 'All geographic markets aligned' },
      { id: 't12', time: 330, type: 'system', title: 'Marketing Directors Ready (15/15)', description: 'Regional marketing teams synchronized' },
      { id: 't13', time: 360, type: 'milestone', title: '30 Stakeholders Acknowledged', description: 'Majority of global team coordinated' },
      { id: 't14', time: 390, type: 'system', title: 'Go-to-Market Playbooks Distributed', description: 'Regional execution plans shared' },
      { id: 't15', time: 420, type: 'task', title: 'Sales Enablement Materials Shared', description: 'Training and collateral distributed globally' },
      { id: 't16', time: 450, type: 'task', title: 'Product Launch Kits Distributed', description: 'All regions have launch assets' },
      { id: 't17', time: 480, type: 'system', title: 'Channel Partner Briefings Scheduled', description: '15-market partner coordination initiated' },
      { id: 't18', time: 510, type: 'milestone', title: '35 Stakeholders Acknowledged', description: 'Regional execution teams ready' },
      { id: 't19', time: 540, type: 'task', title: 'Regional Pricing Confirmed', description: 'All 15 markets pricing strategy locked' },
      { id: 't20', time: 570, type: 'task', title: 'Inventory Allocation Finalized', description: 'Supply chain ready for launch demand' },
      { id: 't21', time: 600, type: 'system', title: 'Legal Compliance Verified (15 Countries)', description: 'Regulatory requirements met' },
      { id: 't22', time: 630, type: 'milestone', title: '40 Stakeholders Acknowledged', description: 'Launch readiness at 80%' },
      { id: 't23', time: 650, type: 'milestone', title: '80% THRESHOLD REACHED (40/50)', description: 'Operational threshold met - continuing to full coordination' },
      { id: 't24', time: 680, type: 'system', title: 'Media Embargoes Coordinated', description: 'Press timing synchronized globally' },
      { id: 't25', time: 707, type: 'milestone', title: 'ALL REGIONS READY FOR LAUNCH', description: '47 of 50 stakeholders - 15 countries synchronized!' },
    ],
    stakeholderRoster: [
      { id: 1, name: 'Isabella Martinez', role: 'CEO', department: 'Executive', priority: 'Critical', region: 'Global HQ' },
      { id: 2, name: 'Tyler Washington', role: 'CMO', department: 'Marketing', priority: 'Critical', region: 'Global HQ' },
      { id: 3, name: 'Priya Patel', role: 'CPO', department: 'Product', priority: 'Critical', region: 'Global HQ' },
      { id: 4, name: 'Carlos Rivera', role: 'CRO', department: 'Sales', priority: 'Critical', region: 'Global HQ' },
      { id: 5, name: 'Hannah Kim', role: 'CTO', department: 'Technology', priority: 'Critical', region: 'Global HQ' },
      { id: 6, name: 'Lucas Schmidt', role: 'CFO', department: 'Finance', priority: 'Critical', region: 'Global HQ' },
      { id: 7, name: 'Natasha Volkov', role: 'COO', department: 'Operations', priority: 'Critical', region: 'Global HQ' },
      { id: 8, name: 'Brandon Mitchell', role: 'GM North America', department: 'Regional Leadership', priority: 'Critical', region: 'US/Canada' },
      { id: 9, name: 'Sofia Hernandez', role: 'GM Latin America', department: 'Regional Leadership', priority: 'High', region: 'LATAM' },
      { id: 10, name: 'Ricardo Santos', role: 'GM Brazil', department: 'Regional Leadership', priority: 'High', region: 'Brazil' },
      { id: 11, name: 'Emma Thompson', role: 'GM United Kingdom', department: 'Regional Leadership', priority: 'Critical', region: 'UK' },
      { id: 12, name: 'Klaus Mueller', role: 'GM DACH', department: 'Regional Leadership', priority: 'High', region: 'Germany' },
      { id: 13, name: 'Francesca Rossi', role: 'GM Southern Europe', department: 'Regional Leadership', priority: 'High', region: 'Italy/Spain' },
      { id: 14, name: 'Henrik Larsson', role: 'GM Nordics', department: 'Regional Leadership', priority: 'Medium', region: 'Nordic' },
      { id: 15, name: 'Yuki Tanaka', role: 'GM Japan', department: 'Regional Leadership', priority: 'Critical', region: 'Japan' },
      { id: 16, name: 'Li Wei', role: 'GM China', department: 'Regional Leadership', priority: 'Critical', region: 'China' },
      { id: 17, name: 'Raj Sharma', role: 'GM India', department: 'Regional Leadership', priority: 'High', region: 'India' },
      { id: 18, name: 'Siti Abdullah', role: 'GM Southeast Asia', department: 'Regional Leadership', priority: 'High', region: 'Singapore' },
      { id: 19, name: 'James Wong', role: 'GM ANZ', department: 'Regional Leadership', priority: 'Medium', region: 'Australia' },
      { id: 20, name: 'Ashley Cooper', role: 'Marketing Dir NA', department: 'Marketing', priority: 'High', region: 'US/Canada' },
      { id: 21, name: 'Diego Martinez', role: 'Marketing Dir LATAM', department: 'Marketing', priority: 'Medium', region: 'LATAM' },
      { id: 22, name: 'Charlotte Davies', role: 'Marketing Dir UK', department: 'Marketing', priority: 'High', region: 'UK' },
      { id: 23, name: 'Werner Fischer', role: 'Marketing Dir DACH', department: 'Marketing', priority: 'Medium', region: 'Germany' },
      { id: 24, name: 'Marco Bianchi', role: 'Marketing Dir Southern EU', department: 'Marketing', priority: 'Medium', region: 'Italy' },
      { id: 25, name: 'Akira Yamamoto', role: 'Marketing Dir Japan', department: 'Marketing', priority: 'High', region: 'Japan' },
      { id: 26, name: 'Zhang Min', role: 'Marketing Dir China', department: 'Marketing', priority: 'High', region: 'China' },
      { id: 27, name: 'Ananya Gupta', role: 'Marketing Dir India', department: 'Marketing', priority: 'Medium', region: 'India' },
      { id: 28, name: 'Maya Chen', role: 'Marketing Dir SEA', department: 'Marketing', priority: 'Medium', region: 'Singapore' },
      { id: 29, name: 'Oliver Bennett', role: 'VP Product Marketing', department: 'Product', priority: 'High', region: 'Global HQ' },
      { id: 30, name: 'Maya Patel', role: 'Director Product Mgmt', department: 'Product', priority: 'High', region: 'Global HQ' },
      { id: 31, name: 'Ethan Brooks', role: 'Product Launch Manager', department: 'Product', priority: 'High', region: 'Global HQ' },
      { id: 32, name: 'Sophie Laurent', role: 'Director Pricing Strategy', department: 'Strategy', priority: 'High', region: 'Global HQ' },
      { id: 33, name: 'Mateo Garcia', role: 'VP Sales North America', department: 'Sales', priority: 'High', region: 'US/Canada' },
      { id: 34, name: 'Chloe Anderson', role: 'VP Sales EMEA', department: 'Sales', priority: 'High', region: 'UK' },
      { id: 35, name: 'Kenji Sato', role: 'VP Sales APAC', department: 'Sales', priority: 'High', region: 'Japan' },
      { id: 36, name: 'Rachel Green', role: 'Director Channel Partners', department: 'Partnerships', priority: 'High', region: 'Global HQ' },
      { id: 37, name: 'Mark Johnson', role: 'VP Supply Chain', department: 'Operations', priority: 'High', region: 'Global HQ' },
      { id: 38, name: 'Lisa Wang', role: 'Director Inventory', department: 'Operations', priority: 'Medium', region: 'Global HQ' },
      { id: 39, name: 'David Foster', role: 'VP Legal & Compliance', department: 'Legal', priority: 'High', region: 'Global HQ' },
      { id: 40, name: 'Anna Kowalski', role: 'Regulatory Affairs Dir', department: 'Legal', priority: 'High', region: 'Global HQ' },
      { id: 41, name: 'Marcus Lee', role: 'Director Public Relations', department: 'Communications', priority: 'High', region: 'Global HQ' },
      { id: 42, name: 'Jennifer Davis', role: 'Social Media Director', department: 'Marketing', priority: 'Medium', region: 'Global HQ' },
      { id: 43, name: 'Alex Turner', role: 'VP Engineering', department: 'Technology', priority: 'High', region: 'Global HQ' },
      { id: 44, name: 'Samantha White', role: 'Director Release Mgmt', department: 'Technology', priority: 'High', region: 'Global HQ' },
      { id: 45, name: 'Chris Martinez', role: 'VP Customer Success', department: 'Customer Success', priority: 'High', region: 'Global HQ' },
      { id: 46, name: 'Nina Patel', role: 'Training & Enablement Dir', department: 'Customer Success', priority: 'Medium', region: 'Global HQ' },
      { id: 47, name: 'Robert Chang', role: 'VP Finance Operations', department: 'Finance', priority: 'High', region: 'Global HQ' },
      { id: 48, name: 'Laura Kim', role: 'Director Revenue Ops', department: 'Finance', priority: 'Medium', region: 'Global HQ' },
      { id: 49, name: 'Daniel Brown', role: 'VP Business Development', department: 'Strategy', priority: 'Medium', region: 'Global HQ' },
      { id: 50, name: 'Victoria Scott', role: 'Director Market Analytics', department: 'Strategy', priority: 'Medium', region: 'Global HQ' },
    ],
    beforeMetrics: {
      time: "2-3 weeks",
      cost: "$1.2M",
      overhead: "Global time zone chaos"
    },
    afterMetrics: {
      time: "11:47 min",
      cost: "$95K",
      overhead: "Synchronized execution"
    },
    valueProp: "$1.1M saved",
    timeMultiplier: "2,000x faster"
  },

  'supplier-crisis': {
    id: 'supplier-crisis',
    title: "Supplier Crisis - Tier 1 Failure",
    playbook: "Critical Supplier Continuity Response",
    description: "ChipTech (Tier 1 semiconductor supplier) filed Chapter 11. Supplies 40% of our components. Manufacturing stops in 48 hours without alternative source. Need immediate supply chain response.",
    emoji: "📦",
    targetCompletionTime: 707,
    tasks: [
      { id: 't1', time: 0, type: 'milestone', title: 'Supplier Crisis Playbook Activated', description: 'CPO triggered emergency supply chain response' },
      { id: 't2', time: 15, type: 'system', title: '35 Stakeholders Alerted: URGENT', description: 'Crisis management team mobilized' },
      { id: 't3', time: 30, type: 'task', title: 'CEO Acknowledged', description: 'Executive leadership engaged' },
      { id: 't4', time: 45, type: 'task', title: 'COO Acknowledged', description: 'Operations continuity activated' },
      { id: 't5', time: 60, type: 'task', title: 'CPO Acknowledged: Activating Contingency', description: 'Alternative supplier protocol initiated' },
      { id: 't6', time: 80, type: 'task', title: 'CFO Acknowledged: Emergency Budget Approved', description: '$5M expedited procurement authorized' },
      { id: 't7', time: 105, type: 'milestone', title: 'C-Suite Coordinated (6/6 = 100%)', description: 'All executive stakeholders aligned' },
      { id: 't8', time: 120, type: 'system', title: 'Crisis War Room Established', description: 'Central command center for response coordination' },
      { id: 't9', time: 150, type: 'system', title: 'Alternative Supplier List Distributed', description: 'Pre-qualified backup vendors identified' },
      { id: 't10', time: 180, type: 'task', title: 'Director Procurement Acknowledged', description: 'Supplier negotiations underway' },
      { id: 't11', time: 210, type: 'task', title: 'Manufacturing Operations Ready', description: 'Production rescheduling initiated' },
      { id: 't12', time: 240, type: 'milestone', title: '5 Plant Managers Coordinated', description: 'All facilities aligned on contingency plans' },
      { id: 't13', time: 270, type: 'system', title: 'Inventory Assessment: 48 Hours Supply', description: 'Critical timeline confirmed' },
      { id: 't14', time: 300, type: 'milestone', title: '15 Stakeholders Acknowledged', description: 'Core response team coordinated' },
      { id: 't15', time: 330, type: 'task', title: 'Alternative Supplier #1 Contacted', description: 'SemiconductorCo engaged for emergency supply' },
      { id: 't16', time: 360, type: 'task', title: 'Alternative Supplier #2 Contacted', description: 'ChipSource international engaged' },
      { id: 't17', time: 390, type: 'task', title: 'Alternative Supplier #3 Contacted', description: 'GlobalChip ready for expedited delivery' },
      { id: 't18', time: 420, type: 'system', title: 'Quality Team Reviewing Alternatives', description: 'Component certification expedited' },
      { id: 't19', time: 450, type: 'milestone', title: '20 Stakeholders Acknowledged', description: 'Procurement and operations aligned' },
      { id: 't20', time: 480, type: 'task', title: 'Expedited Procurement Authorized', description: 'Air freight and premium pricing approved' },
      { id: 't21', time: 510, type: 'system', title: 'Production Rescheduling Underway', description: 'Manufacturing adjusted for supply timeline' },
      { id: 't22', time: 540, type: 'task', title: 'Customer Impact Assessment Complete', description: 'Zero customer delays projected' },
      { id: 't23', time: 570, type: 'milestone', title: '25 Stakeholders Acknowledged', description: 'Supply chain response at scale' },
      { id: 't24', time: 600, type: 'system', title: 'Air Freight Arranged for Emergency Supply', description: '36-hour delivery confirmed' },
      { id: 't25', time: 630, type: 'milestone', title: '28 Stakeholders Acknowledged', description: 'Crisis response team at 80%' },
      { id: 't26', time: 650, type: 'milestone', title: '80% THRESHOLD REACHED (28/35)', description: 'Operational coordination threshold met' },
      { id: 't27', time: 680, type: 'system', title: 'Alternative Supplier Commitments Secured', description: 'Supply continuity confirmed' },
      { id: 't28', time: 707, type: 'milestone', title: 'SUPPLY CHAIN RESPONSE COORDINATED', description: '33 of 35 stakeholders - crisis averted!' },
    ],
    stakeholderRoster: [
      { id: 1, name: 'Victoria Sterling', role: 'CEO', department: 'Executive', priority: 'Critical' },
      { id: 2, name: 'Marcus Thompson', role: 'COO', department: 'Operations', priority: 'Critical' },
      { id: 3, name: 'Elena Rodriguez', role: 'CPO', department: 'Procurement', priority: 'Critical' },
      { id: 4, name: 'James Patterson', role: 'CFO', department: 'Finance', priority: 'Critical' },
      { id: 5, name: 'Sophia Chang', role: 'CTO', department: 'Technology', priority: 'Critical' },
      { id: 6, name: 'Robert Kim', role: 'General Counsel', department: 'Legal', priority: 'Critical' },
      { id: 7, name: 'Catherine Brooks', role: 'VP Supply Chain', department: 'Supply Chain', priority: 'Critical' },
      { id: 8, name: 'Derek Martinez', role: 'Director Procurement', department: 'Procurement', priority: 'Critical' },
      { id: 9, name: 'Michelle Foster', role: 'Director Supplier Relations', department: 'Procurement', priority: 'High' },
      { id: 10, name: 'Andrew Sullivan', role: 'Strategic Sourcing Manager', department: 'Procurement', priority: 'High' },
      { id: 11, name: 'Lisa Anderson', role: 'Commodity Manager - Semiconductors', department: 'Procurement', priority: 'Critical' },
      { id: 12, name: 'Gregory Walsh', role: 'VP Manufacturing', department: 'Manufacturing', priority: 'Critical' },
      { id: 13, name: 'Rachel Green', role: 'Plant Manager - Texas', department: 'Manufacturing', priority: 'High' },
      { id: 14, name: 'Kevin Moore', role: 'Plant Manager - Ohio', department: 'Manufacturing', priority: 'High' },
      { id: 15, name: 'Amanda Scott', role: 'Plant Manager - California', department: 'Manufacturing', priority: 'High' },
      { id: 16, name: 'Christopher Lee', role: 'Plant Manager - Georgia', department: 'Manufacturing', priority: 'High' },
      { id: 17, name: 'Jennifer Davis', role: 'Plant Manager - Michigan', department: 'Manufacturing', priority: 'High' },
      { id: 18, name: 'Michael Turner', role: 'Director Production Planning', department: 'Manufacturing', priority: 'High' },
      { id: 19, name: 'Dr. Sarah Williams', role: 'VP Quality Assurance', department: 'Quality', priority: 'High' },
      { id: 20, name: 'Brian Harris', role: 'Director Component Engineering', department: 'Engineering', priority: 'High' },
      { id: 21, name: 'Nicole Johnson', role: 'Component Quality Lead', department: 'Quality', priority: 'High' },
      { id: 22, name: 'Daniel White', role: 'VP Logistics', department: 'Logistics', priority: 'High' },
      { id: 23, name: 'Patricia Clark', role: 'Director Inventory Management', department: 'Logistics', priority: 'High' },
      { id: 24, name: 'Steven Lewis', role: 'Director Warehousing', department: 'Logistics', priority: 'Medium' },
      { id: 25, name: 'Angela Robinson', role: 'VP Finance Operations', department: 'Finance', priority: 'High' },
      { id: 26, name: 'Thomas Baker', role: 'Director Contracts', department: 'Legal', priority: 'High' },
      { id: 27, name: 'Laura Miller', role: 'Director Risk Management', department: 'Risk', priority: 'High' },
      { id: 28, name: 'David Young', role: 'VP Customer Operations', department: 'Customer Operations', priority: 'High' },
      { id: 29, name: 'Michelle Carter', role: 'Director Customer Communications', department: 'Customer Operations', priority: 'Medium' },
      { id: 30, name: 'Christopher King', role: 'VP Sales Operations', department: 'Sales', priority: 'Medium' },
      { id: 31, name: 'Jennifer Wright', role: 'Director Demand Planning', department: 'Operations', priority: 'High' },
      { id: 32, name: 'Ryan Hall', role: 'Director Materials Management', department: 'Operations', priority: 'High' },
      { id: 33, name: 'Amy Scott', role: 'Quality Certification Manager', department: 'Quality', priority: 'Medium' },
      { id: 34, name: 'Brian Adams', role: 'Director Strategic Sourcing', department: 'Procurement', priority: 'High' },
      { id: 35, name: 'Sandra Mitchell', role: 'Crisis Communications Lead', department: 'Communications', priority: 'Medium' },
    ],
    beforeMetrics: {
      time: "72-96h",
      cost: "$8.7M",
      overhead: "Production shutdown risk"
    },
    afterMetrics: {
      time: "11:47 min",
      cost: "$5.2M",
      overhead: "Crisis averted"
    },
    valueProp: "$3.5M saved",
    timeMultiplier: "450x faster"
  },

  'competitive-response': {
    id: 'competitive-response',
    title: "Competitive Response - Rival Announces Major Product",
    playbook: "Competitive Threat Response Playbook",
    description: "Rival launched next-gen AI platform at 50% lower price. Market reacting. Need immediate competitive response strategy across product, pricing, and go-to-market.",
    emoji: "⚔️",
    targetCompletionTime: 707,
    tasks: [
      { id: 't1', time: 0, type: 'milestone', title: 'Competitive Response Activated', description: 'CMO triggered immediate response coordination' },
      { id: 't2', time: 15, type: 'system', title: 'War Room Created - 32 Stakeholders', description: 'Cross-functional response team assembled' },
      { id: 't3', time: 30, type: 'task', title: 'CEO Acknowledged', description: 'Executive leadership engaged' },
      { id: 't4', time: 45, type: 'task', title: 'CMO Briefing Complete', description: 'Competitive intelligence shared' },
      { id: 't5', time: 60, type: 'task', title: 'CPO Response Plan Initiated', description: 'Product roadmap acceleration underway' },
      { id: 't6', time: 90, type: 'milestone', title: 'C-Suite Aligned (5/5)', description: 'All executives on response strategy' },
      { id: 't7', time: 120, type: 'system', title: 'Competitive Analysis Distributed', description: 'Market intelligence shared with all teams' },
      { id: 't8', time: 150, type: 'task', title: 'Pricing Team Response Ready', description: 'Counter-pricing strategy developed' },
      { id: 't9', time: 180, type: 'milestone', title: 'Product Team Coordinated', description: 'Roadmap acceleration approved' },
      { id: 't10', time: 210, type: 'task', title: 'Sales Battlecard Created', description: 'Competitive positioning materials ready' },
      { id: 't11', time: 240, type: 'system', title: 'Customer Retention Plan Activated', description: 'At-risk account protection initiated' },
      { id: 't12', time: 270, type: 'milestone', title: '15 Stakeholders Coordinated', description: 'Core response team aligned' },
      { id: 't13', time: 300, type: 'task', title: 'Marketing Campaign Approved', description: 'Differentiation messaging ready' },
      { id: 't14', time: 330, type: 'task', title: 'Partnership Team Mobilized', description: 'Ecosystem response coordinated' },
      { id: 't15', time: 360, type: 'system', title: 'Product Announcement Scheduled', description: 'Counter-launch timing confirmed' },
      { id: 't16', time: 390, type: 'milestone', title: '20 Stakeholders Coordinated', description: 'Majority of response team ready' },
      { id: 't17', time: 420, type: 'task', title: 'Sales Enablement Complete', description: 'Field teams trained on response' },
      { id: 't18', time: 450, type: 'task', title: 'Customer Success Outreach Started', description: 'Proactive customer engagement underway' },
      { id: 't19', time: 480, type: 'system', title: 'PR Strategy Approved', description: 'Media response plan ready' },
      { id: 't20', time: 510, type: 'milestone', title: '24 Stakeholders Coordinated', description: 'Response execution at scale' },
      { id: 't21', time: 540, type: 'task', title: 'Product Roadmap Accelerated', description: 'Key features moved to Q1' },
      { id: 't22', time: 570, type: 'task', title: 'Pricing Adjustments Approved', description: 'Competitive pricing strategy locked' },
      { id: 't23', time: 600, type: 'milestone', title: '26 Stakeholders Coordinated', description: 'Response team at 80%+' },
      { id: 't24', time: 630, type: 'system', title: 'Go-to-Market Plan Finalized', description: 'Counter-launch strategy complete' },
      { id: 't25', time: 650, type: 'milestone', title: '80% THRESHOLD REACHED (26/32)', description: 'Operational coordination complete' },
      { id: 't26', time: 680, type: 'task', title: 'Executive Briefing Materials Ready', description: 'Board and investor communications prepared' },
      { id: 't27', time: 707, type: 'milestone', title: 'COMPETITIVE RESPONSE COORDINATED', description: '30 of 32 stakeholders - ready to execute!' },
    ],
    stakeholderRoster: [
      { id: 1, name: 'Alexandra Hunt', role: 'CEO', department: 'Executive', priority: 'Critical' },
      { id: 2, name: 'Jonathan Blake', role: 'CMO', department: 'Marketing', priority: 'Critical' },
      { id: 3, name: 'Dr. Michelle Park', role: 'CPO', department: 'Product', priority: 'Critical' },
      { id: 4, name: 'Richard Foster', role: 'CRO', department: 'Sales', priority: 'Critical' },
      { id: 5, name: 'Stephanie Morrison', role: 'CFO', department: 'Finance', priority: 'Critical' },
      { id: 6, name: 'Marcus Williams', role: 'Chief Strategy Officer', department: 'Strategy', priority: 'Critical' },
      { id: 7, name: 'David Chen', role: 'VP Product Management', department: 'Product', priority: 'Critical' },
      { id: 8, name: 'Emily Rodriguez', role: 'VP Product Marketing', department: 'Marketing', priority: 'Critical' },
      { id: 9, name: 'Thomas Anderson', role: 'VP Competitive Intelligence', department: 'Strategy', priority: 'High' },
      { id: 10, name: 'Sarah Mitchell', role: 'Director Pricing Strategy', department: 'Pricing', priority: 'Critical' },
      { id: 11, name: 'James Sullivan', role: 'VP Sales Strategy', department: 'Sales', priority: 'High' },
      { id: 12, name: 'Rachel Green', role: 'VP Customer Success', department: 'Customer Success', priority: 'High' },
      { id: 13, name: 'Kevin Moore', role: 'Director Sales Enablement', department: 'Sales', priority: 'High' },
      { id: 14, name: 'Jennifer Davis', role: 'Director Market Research', department: 'Marketing', priority: 'High' },
      { id: 15, name: 'Christopher Lee', role: 'VP Engineering', department: 'Engineering', priority: 'High' },
      { id: 16, name: 'Amanda White', role: 'Director Product Strategy', department: 'Product', priority: 'High' },
      { id: 17, name: 'Michael Brown', role: 'VP Brand Marketing', department: 'Marketing', priority: 'High' },
      { id: 18, name: 'Lisa Thompson', role: 'Director Corporate Communications', department: 'Communications', priority: 'High' },
      { id: 19, name: 'Daniel Harris', role: 'VP Partnerships', department: 'Business Development', priority: 'High' },
      { id: 20, name: 'Nicole Johnson', role: 'Director Channel Strategy', department: 'Sales', priority: 'Medium' },
      { id: 21, name: 'Steven Clark', role: 'VP Revenue Operations', department: 'Revenue Ops', priority: 'High' },
      { id: 22, name: 'Patricia Young', role: 'Director Customer Marketing', department: 'Marketing', priority: 'Medium' },
      { id: 23, name: 'Robert King', role: 'VP Field Sales', department: 'Sales', priority: 'High' },
      { id: 24, name: 'Angela Wright', role: 'Director Demand Generation', department: 'Marketing', priority: 'Medium' },
      { id: 25, name: 'Brian Adams', role: 'VP Solutions Engineering', department: 'Pre-Sales', priority: 'Medium' },
      { id: 26, name: 'Laura Martinez', role: 'Director Account Management', department: 'Sales', priority: 'High' },
      { id: 27, name: 'Gregory Scott', role: 'VP Product Development', department: 'Product', priority: 'High' },
      { id: 28, name: 'Michelle Garcia', role: 'Director Analyst Relations', department: 'Marketing', priority: 'Medium' },
      { id: 29, name: 'Andrew Baker', role: 'VP Enterprise Sales', department: 'Sales', priority: 'High' },
      { id: 30, name: 'Victoria Hill', role: 'Director Content Marketing', department: 'Marketing', priority: 'Medium' },
      { id: 31, name: 'Timothy Lewis', role: 'VP Customer Experience', department: 'Customer Success', priority: 'Medium' },
      { id: 32, name: 'Samantha Allen', role: 'Director Win/Loss Analysis', department: 'Strategy', priority: 'Medium' },
    ],
    beforeMetrics: {
      time: "5-7 days",
      cost: "$650K",
      overhead: "Slow, uncoordinated response"
    },
    afterMetrics: {
      time: "11:47 min",
      cost: "$85K",
      overhead: "Rapid, coordinated counter"
    },
    valueProp: "$565K saved",
    timeMultiplier: "600x faster"
  },

  'regulatory-crisis': {
    id: 'regulatory-crisis',
    title: "Regulatory Crisis - FDA Warning Letter",
    playbook: "Regulatory Compliance Emergency Response",
    description: "FDA issued Warning Letter citing quality control deficiencies. 30-day response required. Production hold likely. Coordinating legal, quality, operations for comprehensive response.",
    emoji: "⚖️",
    targetCompletionTime: 707,
    tasks: [
      { id: 't1', time: 0, type: 'milestone', title: 'Regulatory Crisis Response Activated', description: 'CLO triggered emergency compliance response' },
      { id: 't2', time: 15, type: 'system', title: '28 Stakeholders Notified: URGENT', description: 'Compliance crisis team mobilized' },
      { id: 't3', time: 30, type: 'task', title: 'CEO Acknowledged', description: 'Executive leadership engaged' },
      { id: 't4', time: 45, type: 'task', title: 'CLO Crisis Assessment Complete', description: 'Legal implications reviewed' },
      { id: 't5', time: 60, type: 'task', title: 'VP Quality Acknowledged', description: 'Quality systems review initiated' },
      { id: 't6', time: 80, type: 'task', title: 'CFO Budget Approved', description: '$3M remediation budget authorized' },
      { id: 't7', time: 105, type: 'milestone', title: 'Executive Team Coordinated (6/6)', description: 'C-suite aligned on response strategy' },
      { id: 't8', time: 120, type: 'system', title: 'War Room Established', description: 'Compliance command center active' },
      { id: 't9', time: 150, type: 'task', title: 'Regulatory Affairs Team Ready', description: 'FDA response strategy developed' },
      { id: 't10', time: 180, type: 'milestone', title: 'Quality Team Coordinated', description: 'Root cause investigation underway' },
      { id: 't11', time: 210, type: 'system', title: 'External Legal Counsel Engaged', description: 'Regulatory experts briefed' },
      { id: 't12', time: 240, type: 'task', title: 'Manufacturing Hold Implemented', description: 'Production pause for quality review' },
      { id: 't13', time: 270, type: 'milestone', title: '15 Stakeholders Coordinated', description: 'Core compliance team aligned' },
      { id: 't14', time: 300, type: 'system', title: 'CAPA Plan Initiated', description: 'Corrective and preventive actions started' },
      { id: 't15', time: 330, type: 'task', title: 'Quality Audit Scheduled', description: 'Independent third-party review arranged' },
      { id: 't16', time: 360, type: 'task', title: 'Site Remediation Plan Approved', description: 'Facility improvements authorized' },
      { id: 't17', time: 390, type: 'milestone', title: '18 Stakeholders Coordinated', description: 'Operations and quality aligned' },
      { id: 't18', time: 420, type: 'system', title: 'Training Program Revised', description: 'Employee compliance training updated' },
      { id: 't19', time: 450, type: 'task', title: 'Document Control Enhanced', description: 'Quality system improvements implemented' },
      { id: 't20', time: 480, type: 'milestone', title: '21 Stakeholders Coordinated', description: 'Majority of response team ready' },
      { id: 't21', time: 510, type: 'task', title: 'Customer Notification Prepared', description: 'Transparent communication drafted' },
      { id: 't22', time: 540, type: 'system', title: 'Board Briefing Scheduled', description: 'Governance oversight engaged' },
      { id: 't23', time: 570, type: 'task', title: 'FDA Response Draft Complete', description: '30-day response letter prepared' },
      { id: 't24', time: 600, type: 'milestone', title: '23 Stakeholders Coordinated', description: 'Response at 80%+' },
      { id: 't25', time: 630, type: 'system', title: 'Remediation Timeline Locked', description: '90-day improvement plan finalized' },
      { id: 't26', time: 650, type: 'milestone', title: '80% THRESHOLD REACHED (23/28)', description: 'Compliance response coordinated' },
      { id: 't27', time: 680, type: 'task', title: 'External Audit Confirmed', description: 'Third-party verification scheduled' },
      { id: 't28', time: 707, type: 'milestone', title: 'REGULATORY RESPONSE COMPLETE', description: '26 of 28 stakeholders - comprehensive response ready!' },
    ],
    stakeholderRoster: [
      { id: 1, name: 'Dr. Catherine Reynolds', role: 'CEO', department: 'Executive', priority: 'Critical' },
      { id: 2, name: 'Mark Davidson', role: 'Chief Legal Officer', department: 'Legal', priority: 'Critical' },
      { id: 3, name: 'Dr. Susan Harper', role: 'VP Quality Assurance', department: 'Quality', priority: 'Critical' },
      { id: 4, name: 'James Mitchell', role: 'CFO', department: 'Finance', priority: 'Critical' },
      { id: 5, name: 'Patricia Collins', role: 'COO', department: 'Operations', priority: 'Critical' },
      { id: 6, name: 'Dr. Robert Chen', role: 'Chief Scientific Officer', department: 'R&D', priority: 'Critical' },
      { id: 7, name: 'Jennifer Martinez', role: 'VP Regulatory Affairs', department: 'Regulatory', priority: 'Critical' },
      { id: 8, name: 'Michael Anderson', role: 'Director Regulatory Compliance', department: 'Regulatory', priority: 'Critical' },
      { id: 9, name: 'Sarah Thompson', role: 'VP Manufacturing', department: 'Manufacturing', priority: 'Critical' },
      { id: 10, name: 'David Wilson', role: 'Director Quality Control', department: 'Quality', priority: 'Critical' },
      { id: 11, name: 'Lisa Brown', role: 'Director Quality Systems', department: 'Quality', priority: 'High' },
      { id: 12, name: 'Christopher Lee', role: 'Plant Manager - Main Facility', department: 'Manufacturing', priority: 'High' },
      { id: 13, name: 'Amanda Garcia', role: 'Director Document Control', department: 'Quality', priority: 'High' },
      { id: 14, name: 'Thomas Wright', role: 'VP Operations Excellence', department: 'Operations', priority: 'High' },
      { id: 15, name: 'Michelle Davis', role: 'Director Training & Development', department: 'HR', priority: 'High' },
      { id: 16, name: 'Kevin Johnson', role: 'Director Environmental Health & Safety', department: 'EHS', priority: 'High' },
      { id: 17, name: 'Rachel Moore', role: 'VP Supply Chain', department: 'Supply Chain', priority: 'High' },
      { id: 18, name: 'Daniel White', role: 'Director Process Engineering', department: 'Engineering', priority: 'High' },
      { id: 19, name: 'Angela Taylor', role: 'Regulatory Counsel', department: 'Legal', priority: 'High' },
      { id: 20, name: 'Brian Harris', role: 'Director Validation', department: 'Quality', priority: 'High' },
      { id: 21, name: 'Nicole Clark', role: 'Director Laboratory Services', department: 'Quality', priority: 'Medium' },
      { id: 22, name: 'Steven Lewis', role: 'Director Technical Services', department: 'Operations', priority: 'Medium' },
      { id: 23, name: 'Laura Allen', role: 'VP Corporate Communications', department: 'Communications', priority: 'High' },
      { id: 24, name: 'Gregory King', role: 'Director Audit & Inspection', department: 'Quality', priority: 'High' },
      { id: 25, name: 'Samantha Young', role: 'VP Customer Quality', department: 'Quality', priority: 'Medium' },
      { id: 26, name: 'Andrew Scott', role: 'Director CAPA Management', department: 'Quality', priority: 'High' },
      { id: 27, name: 'Victoria Adams', role: 'Compliance Training Manager', department: 'Quality', priority: 'Medium' },
      { id: 28, name: 'Richard Baker', role: 'Director Risk Management', department: 'Risk', priority: 'High' },
    ],
    beforeMetrics: {
      time: "10-14 days",
      cost: "$4.2M",
      overhead: "Production shutdown, reputation damage"
    },
    afterMetrics: {
      time: "11:47 min",
      cost: "$3.1M",
      overhead: "Coordinated response, minimal disruption"
    },
    valueProp: "$1.1M saved",
    timeMultiplier: "1,200x faster"
  },

  'customer-crisis': {
    id: 'customer-crisis',
    title: "Customer Crisis - Enterprise Client Escalation",
    playbook: "Major Account Crisis Response",
    description: "Fortune 100 client (40% of revenue) experiencing critical system failures. Threatening to churn. CEO-to-CEO escalation. Need immediate cross-functional response to save account.",
    emoji: "🚨",
    targetCompletionTime: 707,
    tasks: [
      { id: 't1', time: 0, type: 'milestone', title: 'Customer Crisis Playbook Activated', description: 'CRO triggered executive account rescue' },
      { id: 't2', time: 15, type: 'system', title: '24 Stakeholders Alerted: CODE RED', description: 'Account rescue team assembled' },
      { id: 't3', time: 30, type: 'task', title: 'CEO Acknowledged', description: 'CEO-to-CEO call scheduled within 2 hours' },
      { id: 't4', time: 45, type: 'task', title: 'CRO War Room Active', description: 'Revenue leadership coordinating response' },
      { id: 't5', time: 60, type: 'task', title: 'CTO Engineering Team Mobilized', description: 'Technical root cause investigation started' },
      { id: 't6', time: 80, type: 'milestone', title: 'Executive Team Coordinated (5/5)', description: 'C-suite aligned on rescue plan' },
      { id: 't7', time: 105, type: 'system', title: 'Customer Success War Room Created', description: 'Dedicated Slack channel with all stakeholders' },
      { id: 't8', time: 120, type: 'task', title: 'Technical Team On-Site Dispatch', description: 'Engineers flying to customer location' },
      { id: 't9', time: 150, type: 'task', title: 'VP Customer Success Briefed Client', description: 'Accountability and timeline shared' },
      { id: 't10', time: 180, type: 'milestone', title: 'Technical Root Cause Identified', description: 'Integration configuration issue found' },
      { id: 't11', time: 210, type: 'system', title: 'Fix Deployed to Production', description: 'Emergency patch applied and tested' },
      { id: 't12', time: 240, type: 'milestone', title: '12 Stakeholders Coordinated', description: 'Core rescue team aligned' },
      { id: 't13', time: 270, type: 'task', title: 'Customer Verification Complete', description: 'Client confirmed systems operational' },
      { id: 't14', time: 300, type: 'task', title: 'Account Recovery Plan Presented', description: 'Retention package and roadmap shared' },
      { id: 't15', time: 330, type: 'system', title: 'Executive Business Review Scheduled', description: 'QBR moved up for strategic alignment' },
      { id: 't16', time: 360, type: 'milestone', title: '15 Stakeholders Coordinated', description: 'Account team fully aligned' },
      { id: 't17', time: 390, type: 'task', title: 'Product Roadmap Prioritization', description: 'Customer feature requests escalated' },
      { id: 't18', time: 420, type: 'task', title: 'Dedicated Support Assigned', description: 'Premium support package activated' },
      { id: 't19', time: 450, type: 'system', title: 'Monitoring Enhanced', description: 'Proactive alerting for account health' },
      { id: 't20', time: 480, type: 'milestone', title: '18 Stakeholders Coordinated', description: 'Full account rescue coordinated' },
      { id: 't21', time: 510, type: 'task', title: 'Customer Training Scheduled', description: 'Best practices workshop arranged' },
      { id: 't22', time: 540, type: 'task', title: 'Executive Sponsor Assigned', description: 'VP-level relationship owner committed' },
      { id: 't23', time: 570, type: 'milestone', title: '20 Stakeholders Coordinated', description: 'Retention strategy at 80%+' },
      { id: 't24', time: 600, type: 'system', title: 'Success Plan Documented', description: '90-day value realization plan created' },
      { id: 't25', time: 630, type: 'task', title: 'CEO Call Complete: Relationship Restored', description: 'Executive alignment achieved' },
      { id: 't26', time: 650, type: 'milestone', title: '80% THRESHOLD REACHED (20/24)', description: 'Account rescue coordinated' },
      { id: 't27', time: 680, type: 'system', title: 'Renewal Contract Prepared', description: 'Multi-year expansion proposal ready' },
      { id: 't28', time: 707, type: 'milestone', title: 'CUSTOMER CRISIS RESOLVED', description: '23 of 24 stakeholders - account saved!' },
    ],
    stakeholderRoster: [
      { id: 1, name: 'Alexandra Morgan', role: 'CEO', department: 'Executive', priority: 'Critical' },
      { id: 2, name: 'Christopher Bailey', role: 'CRO', department: 'Revenue', priority: 'Critical' },
      { id: 3, name: 'Dr. Emily Foster', role: 'CTO', department: 'Technology', priority: 'Critical' },
      { id: 4, name: 'Marcus Jenkins', role: 'VP Customer Success', department: 'Customer Success', priority: 'Critical' },
      { id: 5, name: 'Sarah Richardson', role: 'CFO', department: 'Finance', priority: 'Critical' },
      { id: 6, name: 'David Patterson', role: 'CPO', department: 'Product', priority: 'High' },
      { id: 7, name: 'Jennifer Lee', role: 'Account Executive - Enterprise', department: 'Sales', priority: 'Critical' },
      { id: 8, name: 'Michael Torres', role: 'Customer Success Manager', department: 'Customer Success', priority: 'Critical' },
      { id: 9, name: 'Rachel Sanders', role: 'VP Engineering', department: 'Engineering', priority: 'Critical' },
      { id: 10, name: 'Kevin Hughes', role: 'Director Support Engineering', department: 'Support', priority: 'Critical' },
      { id: 11, name: 'Amanda Cooper', role: 'Solutions Architect', department: 'Solutions Engineering', priority: 'Critical' },
      { id: 12, name: 'Thomas Wright', role: 'VP Product Management', department: 'Product', priority: 'High' },
      { id: 13, name: 'Lisa Martinez', role: 'Director Enterprise Sales', department: 'Sales', priority: 'High' },
      { id: 14, name: 'Daniel Brooks', role: 'VP Professional Services', department: 'Professional Services', priority: 'High' },
      { id: 15, name: 'Michelle Clark', role: 'Senior Solutions Engineer', department: 'Solutions Engineering', priority: 'High' },
      { id: 16, name: 'Steven Bennett', role: 'Director Customer Operations', department: 'Customer Success', priority: 'High' },
      { id: 17, name: 'Angela Wilson', role: 'VP Revenue Operations', department: 'Revenue Ops', priority: 'High' },
      { id: 18, name: 'Brian Davis', role: 'Implementation Manager', department: 'Professional Services', priority: 'Medium' },
      { id: 19, name: 'Nicole Thompson', role: 'Product Manager - Enterprise', department: 'Product', priority: 'High' },
      { id: 20, name: 'Gregory Moore', role: 'Director Technical Account Management', department: 'Customer Success', priority: 'High' },
      { id: 21, name: 'Samantha White', role: 'VP Marketing', department: 'Marketing', priority: 'Medium' },
      { id: 22, name: 'Andrew King', role: 'Director Customer Training', department: 'Customer Success', priority: 'Medium' },
      { id: 23, name: 'Victoria Adams', role: 'Renewals Manager', department: 'Sales', priority: 'High' },
      { id: 24, name: 'Richard Harris', role: 'Executive Business Advisor', department: 'Customer Success', priority: 'High' },
    ],
    beforeMetrics: {
      time: "48-72h",
      cost: "$12M at risk (churn)",
      overhead: "Account loss, reputation damage"
    },
    afterMetrics: {
      time: "11:47 min",
      cost: "$500K (retention)",
      overhead: "Account saved, relationship restored"
    },
    valueProp: "$11.5M saved",
    timeMultiplier: "300x faster"
  }
};

// Helper function to get scenario by ID
export function getScenarioById(id: string): DemoScenario | null {
  return DEMO_SCENARIOS[id] || null;
}

// Helper function to get all scenario IDs
export function getAllScenarioIds(): string[] {
  return Object.keys(DEMO_SCENARIOS);
}
